export interface GenomeData {
  name: string;
  description: string;
  abilityBonuses: Partial<Record<AbilityKey, number>>;
  senses: Partial<Record<SenseKey, boolean>>;
  traits: { name: string; description: string }[];
  speed: number;
}

export interface ClassData {
  name: string;
  hitDie: number;
  savingThrows: AbilityKey[];
  armorProficiencies: string;
  weaponProficiencies: string;
  skillChoices: string[];
  numSkillChoices: number;
  featuresByLevel: Record<number, { name: string; description: string }[]>;
}

export interface BackgroundData {
  name: string;
  description: string;
  skillProficiencies: string[];
  featureName: string;
  featureDescription: string;
  toolProficiencies?: string;
  languages?: string;
}

export type AbilityKey = 'strength' | 'dexterity' | 'constitution' | 'intelligence' | 'wisdom' | 'charisma';
export type SenseKey = 'acuteOlfaction' | 'darkvision' | 'macrovision' | 'microvision' | 'penetration' | 'spectrum';

export const GENOMES: GenomeData[] = [
  {
    name: "Baseline",
    description: "Unmodified human genome. Versatile and adaptable, Baselines represent the broad genetic heritage of unaltered humanity.",
    abilityBonuses: { strength: 1, dexterity: 1, constitution: 1, intelligence: 1, wisdom: 1, charisma: 1 },
    senses: {},
    traits: [
      { name: "Versatile", description: "You gain proficiency in one skill of your choice." },
      { name: "Determined", description: "When you fail a saving throw, you can reroll it. You must use the new roll. Once you use this trait, you can't use it again until you finish a long rest." },
    ],
    speed: 30,
  },
  {
    name: "Aquaform",
    description: "Spliced with aquatic DNA, Aquaforms possess gills, webbed digits, and enhanced underwater capabilities.",
    abilityBonuses: { constitution: 2, wisdom: 1 },
    senses: { darkvision: true },
    traits: [
      { name: "Amphibious", description: "You can breathe air and water." },
      { name: "Swim Speed", description: "You have a swimming speed of 30 feet." },
      { name: "Pressure Resistant", description: "You have resistance to cold damage." },
    ],
    speed: 30,
  },
  {
    name: "Avian",
    description: "Engineered with avian genetics, granting hollow bones, enhanced vision, and in some cases vestigial wing membranes.",
    abilityBonuses: { dexterity: 2, wisdom: 1 },
    senses: { macrovision: true },
    traits: [
      { name: "Keen Sight", description: "You have advantage on Wisdom (Perception) checks that rely on sight." },
      { name: "Lightweight Frame", description: "You can use your reaction to reduce falling damage by an amount equal to five times your level." },
      { name: "Talons", description: "Your unarmed strikes deal 1d4 slashing damage." },
    ],
    speed: 30,
  },
  {
    name: "Canid",
    description: "Spliced with canine DNA, Canids possess enhanced olfactory senses, pack instincts, and fierce loyalty.",
    abilityBonuses: { wisdom: 2, constitution: 1 },
    senses: { acuteOlfaction: true, darkvision: true },
    traits: [
      { name: "Keen Smell", description: "You have advantage on Wisdom (Perception) checks that rely on smell." },
      { name: "Pack Tactics", description: "You have advantage on attack rolls against a creature if at least one of your allies is within 5 feet of the creature." },
      { name: "Bite", description: "Your unarmed strikes deal 1d6 piercing damage." },
    ],
    speed: 35,
  },
  {
    name: "Felid",
    description: "Feline genetic splicing grants enhanced reflexes, night vision, and preternatural agility.",
    abilityBonuses: { dexterity: 2, charisma: 1 },
    senses: { darkvision: true },
    traits: [
      { name: "Cat's Grace", description: "You have proficiency in the Acrobatics skill." },
      { name: "Feline Agility", description: "When you move on your turn in combat, you can double your speed until the end of the turn. Once you use this trait, you can't use it again until you move 0 feet on one of your turns." },
      { name: "Retractable Claws", description: "Your unarmed strikes deal 1d4 slashing damage." },
    ],
    speed: 30,
  },
  {
    name: "Insectoid",
    description: "Arthropod DNA integration provides a chitinous exoskeleton, compound visual processing, and enhanced durability.",
    abilityBonuses: { constitution: 2, strength: 1 },
    senses: { spectrum: true },
    traits: [
      { name: "Chitin Plating", description: "When you aren't wearing armor, your AC is 13 + your Dexterity modifier." },
      { name: "Compound Eyes", description: "You have advantage on saving throws against being blinded." },
      { name: "Wall Crawler", description: "You have a climbing speed equal to your walking speed." },
    ],
    speed: 30,
  },
  {
    name: "Lacertid",
    description: "Lizard-genome splicing enables rapid cellular regeneration, thermal regulation, and natural camouflage.",
    abilityBonuses: { constitution: 2, intelligence: 1 },
    senses: { penetration: true },
    traits: [
      { name: "Regeneration", description: "At the start of each of your turns, you regain hit points equal to your proficiency bonus if you have at least 1 hit point and no more than half your hit points." },
      { name: "Cold-Blooded", description: "You have resistance to fire damage but vulnerability to cold damage." },
      { name: "Natural Camouflage", description: "You have advantage on Dexterity (Stealth) checks made to hide in natural environments." },
    ],
    speed: 30,
  },
  {
    name: "Ophidian",
    description: "Serpentine genetics grant flexibility, venomous capability, and heat-sensing perception.",
    abilityBonuses: { dexterity: 1, constitution: 1, charisma: 1 },
    senses: { penetration: true },
    traits: [
      { name: "Serpentine Flexibility", description: "You have advantage on checks and saves to escape grapples and restraints." },
      { name: "Venomous Bite", description: "Your unarmed bite attack deals 1d4 piercing damage plus 1d4 poison damage." },
      { name: "Heat Sense", description: "You can detect the presence of warm-blooded creatures within 30 feet, even through walls up to 1 foot thick." },
    ],
    speed: 30,
  },
  {
    name: "Primate",
    description: "Enhanced primate genetics provide superior grip strength, climbing ability, and raw physical power.",
    abilityBonuses: { strength: 2, constitution: 1 },
    senses: {},
    traits: [
      { name: "Powerful Build", description: "You count as one size larger when determining carrying capacity and the weight you can push, drag, or lift." },
      { name: "Climbing Speed", description: "You have a climbing speed of 30 feet." },
      { name: "Prehensile Feet", description: "You can use your feet to manipulate objects, open doors, and wield weapons, freeing your hands." },
    ],
    speed: 30,
  },
  {
    name: "Ursid",
    description: "Bear-genome splicing creates imposing physiques with enhanced endurance and raw physical might.",
    abilityBonuses: { strength: 2, constitution: 2 },
    senses: { acuteOlfaction: true },
    traits: [
      { name: "Thick Hide", description: "You have resistance to bludgeoning damage from nonmagical attacks." },
      { name: "Powerful Maul", description: "Your unarmed strikes deal 1d6 + your Strength modifier bludgeoning damage." },
      { name: "Hibernation Recovery", description: "When you take a long rest, you regain all spent Hit Dice instead of half." },
    ],
    speed: 30,
  },
  {
    name: "Chiropteran",
    description: "Bat-genome integration enables echolocation, enhanced hearing, and limited gliding capability.",
    abilityBonuses: { dexterity: 2, wisdom: 1 },
    senses: { darkvision: true, spectrum: true },
    traits: [
      { name: "Echolocation", description: "You have blindsight out to 30 feet. You can't use this while deafened." },
      { name: "Keen Hearing", description: "You have advantage on Wisdom (Perception) checks that rely on hearing." },
      { name: "Glide", description: "You can use wing membranes to glide. When falling, you can move 2 feet horizontally for every 1 foot you descend." },
    ],
    speed: 30,
  },
];

export const CLASSES: ClassData[] = [
  {
    name: "Biohacker",
    hitDie: 8,
    savingThrows: ["intelligence", "wisdom"],
    armorProficiencies: "Light armor",
    weaponProficiencies: "Simple weapons, Simple firearms, Syringes",
    skillChoices: ["acrobatics", "insight", "investigation", "lifeScience", "medicine", "perception", "physicalScience", "stealth"],
    numSkillChoices: 3,
    featuresByLevel: {
      1: [
        { name: "Hacking", description: "You can run biological hacks — engineered nano-programs that interface with living systems. You prepare a number of biohacker hacks equal to your Intelligence modifier + half your biohacker level (rounded down, minimum 1). You regain all expended hack slots when you finish a long rest." },
        { name: "Hack Recovery", description: "Once per day when you finish a short rest, you can recover hack slots with a combined level equal to half your biohacker level (rounded up)." },
      ],
      2: [{ name: "Bio-Modification", description: "You can modify your own biology as a bonus action, granting advantage on one type of saving throw until the start of your next turn." }],
      3: [{ name: "Biohacker Archetype", description: "You choose a biohacker archetype: Cytomancer (cellular manipulation and transformation), Dr. Frankenstein (reanimation and enhancement of constructs), or Protean Grinder (adaptive genetic mutation). Your archetype grants features at 3rd, 7th, 11th, and 15th level." }],
      4: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      5: [{ name: "Upgrade Protocols", description: "You can apply cybernetic upgrades to yourself or willing creatures during a short or long rest without a medical kit." }],
      6: [{ name: "Archetype Feature", description: "You gain a feature from your biohacker archetype." }],
      7: [{ name: "Archetype Feature", description: "You gain a feature from your biohacker archetype." }],
      8: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      9: [{ name: "Advanced Biosystems", description: "You gain access to 3rd-level biohacker hacks. Your nano-programs can now affect multiple targets or produce more complex biological effects." }],
      10: [{ name: "Genome Mastery", description: "You have resistance to poison damage and advantage on saving throws against disease and the poisoned condition." }],
      11: [{ name: "Archetype Feature", description: "You gain a feature from your biohacker archetype." }],
      12: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      13: [{ name: "Adaptive Immunity", description: "You can expend a hack slot to grant yourself or a creature within touch advantage on Constitution saving throws for 1 hour." }],
      14: [{ name: "Bio-Fortification", description: "Your hit point maximum increases by an amount equal to your biohacker level." }],
      15: [{ name: "Archetype Feature", description: "You gain a feature from your biohacker archetype." }],
      16: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      17: [{ name: "Grand Design", description: "You can run two hacks in a single action once per long rest." }],
      18: [{ name: "Biotic Transcendence", description: "You no longer need to eat, drink, or sleep. You are also immune to disease." }],
      19: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      20: [{ name: "Singularity of Flesh", description: "Your biological mastery is absolute. You can change your genome type once per long rest, adopting the traits of any genome for 24 hours." }],
    },
  },
  {
    name: "Codehacker",
    hitDie: 6,
    savingThrows: ["intelligence", "dexterity"],
    armorProficiencies: "Light armor",
    weaponProficiencies: "Daggers, Light pistols, Simple firearms, Simple weapons",
    skillChoices: ["computers", "deception", "investigation", "mechanics", "perception", "sleightOfHand", "stealth", "streetwise"],
    numSkillChoices: 3,
    featuresByLevel: {
      1: [
        { name: "Hacking", description: "You can run software hacks — intrusive code programs deployed through your neural interface. You know a number of codehacker hacks equal to your Intelligence modifier + your codehacker level. You regain all expended hack slots when you finish a long rest." },
        { name: "Neural Interface", description: "Your brain has been modified with a hacking neural interface. You can connect to any networked device within 9 meters as a bonus action. You have advantage on Intelligence (Computers) checks." },
      ],
      2: [{ name: "Digital Ghost", description: "You can mask your digital footprint. You have advantage on Intelligence (Computers) checks to avoid detection while actively hacking a system." }],
      3: [{ name: "Codehacker Specialty", description: "You choose a hacking specialty: Cracker (brute-force intrusion and ICE destruction), Puppeteer (taking control of systems and drones), or Synergist (enhancing your cadre's network and equipment). Your specialty grants features at 3rd, 7th, 11th, and 15th level." }],
      4: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      5: [{ name: "Overclocked Mind", description: "Your processing speed allows you to launch a hack as a bonus action once per turn." }],
      6: [{ name: "Specialty Feature", description: "You gain a feature from your codehacker specialty." }],
      7: [{ name: "Specialty Feature", description: "You gain a feature from your codehacker specialty." }],
      8: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      9: [{ name: "Advanced Intrusion", description: "You gain access to 3rd-level software hacks and can hack hardened military-grade ICE." }],
      10: [{ name: "Firewall", description: "You can erect a digital firewall as a reaction, granting yourself or an ally within 9 meters resistance to damage from a hack or technological attack. Usable a number of times equal to your Intelligence modifier per long rest." }],
      11: [{ name: "Specialty Feature", description: "You gain a feature from your codehacker specialty." }],
      12: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      13: [{ name: "Ghost Protocol", description: "You can become undetectable on any network for up to 1 hour. No automated system or AI can detect your presence during this time." }],
      14: [{ name: "Neural Fortress", description: "Your mind is hardened against counter-intrusion. You have advantage on saving throws against mind-affecting hacks and are immune to having your neural interface hijacked." }],
      15: [{ name: "Specialty Feature", description: "You gain a feature from your codehacker specialty." }],
      16: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      17: [{ name: "Parallel Processing", description: "You can concentrate on two hacks simultaneously." }],
      18: [{ name: "Master Hack", description: "Once per long rest, you can run a hack without expending a hack slot." }],
      19: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      20: [{ name: "Omnipotent Node", description: "You can simultaneously control up to three networked systems or drones at once. Your Computers checks automatically succeed on natural rolls of 10 or higher." }],
    },
  },
  {
    name: "Crook",
    hitDie: 8,
    savingThrows: ["dexterity", "intelligence"],
    armorProficiencies: "Light armor",
    weaponProficiencies: "Simple weapons, Simple firearms, Hand crossbows, Mono-blades, Shortswords",
    skillChoices: ["acrobatics", "athletics", "bureaucracy", "deception", "insight", "intimidation", "investigation", "perception", "persuasion", "sleightOfHand", "stealth", "streetwise"],
    numSkillChoices: 4,
    featuresByLevel: {
      1: [
        { name: "Expertise", description: "Choose two of your skill proficiencies. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies." },
        { name: "Illicit Contacts", description: "You have a network of criminal contacts. You gain 2 Illicit Contacts — underworld figures who can provide you with information, equipment, and favors." },
        { name: "Sneak Attack", description: "Once per turn you can deal extra damage to one creature you hit with a finesse or ranged weapon if you have advantage on the attack roll. The extra damage is 1d6, and increases as you gain crook levels." },
      ],
      2: [{ name: "Cunning Action", description: "You can use a bonus action to take the Dash, Disengage, or Hide action." }],
      3: [{ name: "Crook Archetype", description: "You choose a criminal archetype: Dealer (information broker and black-market specialist), Hitman (contract killer and assassin), or Robber (heist expert and getaway driver). Your archetype grants features at 3rd, 9th, 13th, and 17th level." }],
      4: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      5: [{ name: "Uncanny Dodge", description: "When an attacker you can see hits you with an attack, you can use your reaction to halve the attack's damage against you." }],
      6: [{ name: "Expertise (2)", description: "Choose two more of your skill proficiencies to gain expertise in." }],
      7: [{ name: "Evasion", description: "When you are subjected to an effect that allows you to make a Dexterity saving throw to take only half damage, you instead take no damage if you succeed on the saving throw, and only half damage if you fail." }],
      8: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      9: [{ name: "Archetype Feature", description: "You gain a feature from your crook archetype." }],
      10: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      11: [{ name: "Reliable Talent", description: "Whenever you make an ability check that lets you add your proficiency bonus, you can treat a d20 roll of 9 or lower as a 10." }],
      12: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      13: [{ name: "Archetype Feature", description: "You gain a feature from your crook archetype." }],
      14: [{ name: "Blindsense", description: "If you are able to hear, you are aware of the location of any hidden or invisible creature within 3 meters of you." }],
      15: [{ name: "Slippery Mind", description: "You gain proficiency in Wisdom saving throws." }],
      16: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      17: [{ name: "Archetype Feature", description: "You gain a feature from your crook archetype." }],
      18: [{ name: "Elusive", description: "No attack roll has advantage against you while you aren't incapacitated." }],
      19: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      20: [{ name: "Ghost", description: "You have mastered the art of disappearing. When you are hidden, enemies have disadvantage on Perception checks to find you. Additionally, you can use a bonus action to attempt to hide after taking the Attack action." }],
    },
  },
  {
    name: "Engineer",
    hitDie: 8,
    savingThrows: ["intelligence", "constitution"],
    armorProficiencies: "Light armor, Medium armor",
    weaponProficiencies: "Simple weapons, Simple firearms, Hand crossbows",
    skillChoices: ["computers", "drive", "insight", "investigation", "mechanics", "perception", "physicalScience", "streetwise"],
    numSkillChoices: 3,
    featuresByLevel: {
      1: [
        { name: "Hacking", description: "You can run tech hacks — programs and scripts that interface with electronic systems, drones, and vehicles. You prepare a number of engineer hacks equal to your Intelligence modifier + half your engineer level (rounded down, minimum 1). You regain all expended hack slots when you finish a long rest." },
        { name: "Gadgeteer", description: "You can craft improvised gadgets during a short rest using salvaged materials. Crafted gadgets can replicate simple equipment or low-level hacks." },
      ],
      2: [{ name: "Drone Specialist", description: "You gain proficiency with drone operation. You can remotely control drones within 90 meters, and your drones gain bonus hit points equal to your Intelligence modifier." }],
      3: [{ name: "Engineer Archetype", description: "You choose an engineering archetype: Gadgeteer (experimental device crafter), Gearhead (vehicle and mechanical expert), or Roboticist (combat drone and synthetic companion builder). Your archetype grants features at 3rd, 7th, 11th, and 15th level." }],
      4: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      5: [{ name: "Overdrive", description: "You can push a device or drone beyond its limits. As a bonus action, you can grant a drone or vehicle within 9 meters an additional action this turn, or give it temporary hit points equal to your engineer level." }],
      6: [{ name: "Archetype Feature", description: "You gain a feature from your engineer archetype." }],
      7: [{ name: "Archetype Feature", description: "You gain a feature from your engineer archetype." }],
      8: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      9: [{ name: "Advanced Systems", description: "You gain access to 3rd-level engineer hacks. Your device crafting now produces military-grade equipment." }],
      10: [{ name: "Jury Rig", description: "You can repair a broken device or vehicle component as a bonus action. You can also stabilize a drone with 0 HP as an action." }],
      11: [{ name: "Archetype Feature", description: "You gain a feature from your engineer archetype." }],
      12: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      13: [{ name: "Modular Chassis", description: "You can redesign and refit drones or vehicles over a short rest, changing their loadouts without additional cost." }],
      14: [{ name: "Saboteur", description: "When you hack a device or vehicle, you can choose to cause it to malfunction. Malfunctioning devices deal half damage to nearby creatures or impose the stunned condition on their operators." }],
      15: [{ name: "Archetype Feature", description: "You gain a feature from your engineer archetype." }],
      16: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      17: [{ name: "Swarm Protocol", description: "You can control up to three drones simultaneously without penalty." }],
      18: [{ name: "Master Engineer", description: "Once per long rest, you can craft a complex device in 10 minutes that would otherwise take hours." }],
      19: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      20: [{ name: "Apex Constructor", description: "Your drones and devices have their maximum hit points doubled. Once per long rest, you can deploy an experimental superweapon device that deals 10d10 damage in a 6-meter radius." }],
    },
  },
  {
    name: "Gunfighter",
    hitDie: 10,
    savingThrows: ["dexterity", "constitution"],
    armorProficiencies: "Light armor, Medium armor",
    weaponProficiencies: "Simple weapons, Martial weapons, All firearms",
    skillChoices: ["acrobatics", "athletics", "drive", "insight", "intimidation", "perception", "stealth", "streetwise", "survival"],
    numSkillChoices: 3,
    featuresByLevel: {
      1: [
        { name: "Fighting Style", description: "You adopt a particular style of fighting as your specialty. Choose from: Dueling (melee), Defense, Great Weapon Fighting, Two-Weapon Fighting, Archery (ranged firearms), or Blind Fighting." },
        { name: "Second Wind", description: "On your turn, you can use a bonus action to regain hit points equal to 1d10 + your gunfighter level. You must finish a short or long rest before using this feature again." },
      ],
      2: [{ name: "Action Surge", description: "On your turn, you can take one additional action. Once you use this feature, you must finish a short or long rest before using it again." }],
      3: [{ name: "Gunfighter Archetype", description: "You choose a gunfighter archetype: Gunslinger (lightning-fast pistol specialist), Sniper (long-range precision shooter), or Soldier (military tactics and heavy weaponry). Your archetype grants features at 3rd, 7th, 10th, 15th, and 18th level." }],
      4: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      5: [{ name: "Extra Attack", description: "You can attack twice, instead of once, whenever you take the Attack action on your turn." }],
      6: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      7: [{ name: "Archetype Feature", description: "You gain a feature from your gunfighter archetype." }],
      8: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      9: [{ name: "Indomitable", description: "You can reroll a saving throw that you fail. If you do so, you must use the new roll. You can use this feature once between long rests." }],
      10: [{ name: "Archetype Feature", description: "You gain a feature from your gunfighter archetype." }],
      11: [{ name: "Extra Attack (2)", description: "You can attack three times whenever you take the Attack action on your turn." }],
      12: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      13: [{ name: "Indomitable (2)", description: "You can use Indomitable twice between long rests." }],
      14: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      15: [{ name: "Archetype Feature", description: "You gain a feature from your gunfighter archetype." }],
      16: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      17: [{ name: "Action Surge (2)", description: "You can use Action Surge twice before a rest." }, { name: "Indomitable (3)", description: "You can use Indomitable three times between long rests." }],
      18: [{ name: "Archetype Feature", description: "You gain a feature from your gunfighter archetype." }],
      19: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      20: [{ name: "Extra Attack (3)", description: "You can attack four times whenever you take the Attack action on your turn." }],
    },
  },
  {
    name: "Hardcase",
    hitDie: 12,
    savingThrows: ["strength", "constitution"],
    armorProficiencies: "Light armor, Medium armor",
    weaponProficiencies: "Simple weapons, Martial weapons, Simple firearms",
    skillChoices: ["athletics", "drive", "insight", "intimidation", "mechanics", "perception", "streetwise", "survival"],
    numSkillChoices: 2,
    featuresByLevel: {
      1: [
        { name: "Unarmored Defense", description: "While you are not wearing any armor, your AC equals 10 + your Dexterity modifier + your Constitution modifier. You can use a shield and still gain this benefit." },
        { name: "Rage", description: "On your turn, you can enter a combat rage as a bonus action. While raging you gain advantage on Strength checks and saving throws, a bonus to melee damage rolls equal to your proficiency bonus, and resistance to bludgeoning, piercing, and slashing damage. Your rage lasts for 1 minute." },
      ],
      2: [{ name: "Reckless Attack", description: "You can throw aside all concern for defense to attack with fierce desperation. When you make your first attack on your turn, you can gain advantage on melee attack rolls, but attack rolls against you have advantage until your next turn." }, { name: "Danger Sense", description: "You have advantage on Dexterity saving throws against effects you can see." }],
      3: [{ name: "Hardcase Archetype", description: "You choose a hardcase archetype: Damage Sponge (unstoppable tank who soaks punishment), Gangster (street enforcer with criminal connections), or Unarmed Fighter (bare-knuckle brawler and martial artist). Your archetype grants features at 3rd, 6th, 10th, and 14th level." }],
      4: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      5: [{ name: "Extra Attack", description: "You can attack twice when you take the Attack action." }, { name: "Fast Movement", description: "Your speed increases by 3 meters while you aren't wearing heavy armor." }],
      6: [{ name: "Archetype Feature", description: "You gain a feature from your hardcase archetype." }],
      7: [{ name: "Feral Instinct", description: "You have advantage on initiative rolls. If you are surprised at the start of combat, you can act normally on your first turn if you enter a rage before doing anything else." }],
      8: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      9: [{ name: "Brutal Critical", description: "You can roll one additional weapon damage die when scoring a critical hit with a melee weapon." }],
      10: [{ name: "Archetype Feature", description: "You gain a feature from your hardcase archetype." }],
      11: [{ name: "Relentless Rage", description: "Your rage can keep you fighting. If you drop to 0 HP while raging and don't die outright, you can make a DC 10 Constitution saving throw. On a success, you drop to 1 HP instead." }],
      12: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      13: [{ name: "Brutal Critical (2)", description: "You roll two additional weapon damage dice on critical hits with melee weapons." }],
      14: [{ name: "Archetype Feature", description: "You gain a feature from your hardcase archetype." }],
      15: [{ name: "Persistent Rage", description: "Your rage is difficult to end early. If you wish to end your rage, you must take no damage for 3 consecutive turns." }],
      16: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      17: [{ name: "Brutal Critical (3)", description: "You roll three additional weapon damage dice on critical hits with melee weapons." }],
      18: [{ name: "Indomitable Might", description: "If your total for a Strength check is less than your Strength score, you can use your Strength score in place of the total." }],
      19: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      20: [{ name: "Primal Champion", description: "Your Strength and Constitution scores increase by 4. Their maximums increase to 24." }],
    },
  },
  {
    name: "Samurai",
    hitDie: 10,
    savingThrows: ["dexterity", "wisdom"],
    armorProficiencies: "Light armor, Medium armor",
    weaponProficiencies: "Simple weapons, Martial melee weapons, Simple firearms, Mono-blades, Katanas",
    skillChoices: ["acrobatics", "athletics", "insight", "intimidation", "perception", "performance", "socialScience", "stealth", "streetwise"],
    numSkillChoices: 3,
    featuresByLevel: {
      1: [
        { name: "Unarmored Defense", description: "While wearing no armor, your AC equals 10 + your Dexterity modifier + your Wisdom modifier. You can wield a weapon and still gain this benefit." },
        { name: "Martial Arts", description: "Your intensive blade training gives you mastery of combat styles using finesse and martial melee weapons. You can use Dexterity instead of Strength for attack and damage rolls with qualifying melee weapons." },
      ],
      2: [
        { name: "Ki", description: "Your training allows you to harness disciplined focus through Ki. You have a number of Ki points equal to your samurai level, which you recover on a short or long rest." },
        { name: "Unarmored Movement", description: "Your speed increases by 3 meters while you are not wearing armor. This increases further as you gain samurai levels." },
      ],
      3: [{ name: "Samurai Archetype", description: "You choose a samurai archetype that defines your style of blade mastery. Your archetype grants features at 3rd, 6th, 11th, and 17th level." }, { name: "Deflect Projectiles", description: "You can use your reaction to deflect a ranged weapon attack. When you do so, the damage is reduced by 1d10 + your Dexterity modifier + your samurai level." }],
      4: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }, { name: "Slow Fall", description: "You can use your reaction when you fall to reduce falling damage by an amount equal to five times your samurai level." }],
      5: [{ name: "Extra Attack", description: "You can attack twice when you take the Attack action." }, { name: "Stunning Strike", description: "When you hit a creature with a melee weapon attack, you can spend 1 Ki point to attempt a stunning strike. The target must succeed on a Constitution saving throw or be stunned until the end of your next turn." }],
      6: [{ name: "Ki-Empowered Strikes", description: "Your melee weapon attacks count as enhanced (non-mundane) for the purpose of overcoming damage reduction." }, { name: "Archetype Feature", description: "You gain a feature from your samurai archetype." }],
      7: [{ name: "Evasion", description: "When subjected to an effect that allows a Dexterity saving throw for half damage, you take no damage on a success and half on a failure." }, { name: "Stillness of Mind", description: "You can use your action to end one charmed or frightened effect on yourself." }],
      8: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      9: [{ name: "Unarmored Movement Improvement", description: "You can move along vertical surfaces and across liquids on your turn without falling during the move." }],
      10: [{ name: "Purity of Mind", description: "Your discipline makes you immune to disease and grants advantage on saves against being frightened or charmed." }],
      11: [{ name: "Archetype Feature", description: "You gain a feature from your samurai archetype." }],
      12: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      13: [{ name: "Blade Mastery", description: "You may reroll any damage die result of 1 or 2 on a melee attack. You must use the second result." }],
      14: [{ name: "Diamond Discipline", description: "You gain proficiency in all saving throws. Additionally, when you make a saving throw and fail, you can spend 1 Ki point to reroll it and use the second result." }],
      15: [{ name: "Timeless Body", description: "Your Ki sustains you. You do not age, and you cannot be magically aged." }],
      16: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      17: [{ name: "Archetype Feature", description: "You gain a feature from your samurai archetype." }],
      18: [{ name: "Empty Mind", description: "You can spend 4 Ki points to become immune to all mental effects and scrying for 1 minute." }],
      19: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      20: [{ name: "Perfect Self", description: "When you roll initiative and have no Ki points remaining, you regain 4 Ki points. Additionally, you can make one additional melee attack whenever you take the Attack action." }],
    },
  },
  {
    name: "Suit",
    hitDie: 8,
    savingThrows: ["charisma", "wisdom"],
    armorProficiencies: "Light armor",
    weaponProficiencies: "Simple weapons, Simple firearms, Sidearms",
    skillChoices: ["bureaucracy", "deception", "drive", "insight", "intimidation", "investigation", "perception", "performance", "persuasion", "socialScience", "streetwise"],
    numSkillChoices: 4,
    featuresByLevel: {
      1: [
        { name: "Corporate Network", description: "You maintain a network of professional contacts. You gain 2 Contacts — influential figures in megacorporations, government agencies, or organized crime who owe you favors." },
        { name: "Situational Awareness", description: "You are rarely caught off guard. You can add your Charisma modifier to your initiative rolls." },
      ],
      2: [
        { name: "Jack of All Trades", description: "You can add half your proficiency bonus (rounded down) to any ability check you make that doesn't already include your proficiency bonus." },
        { name: "Inspire Allies", description: "As a bonus action, you can inspire an ally within 18 meters. They can add a d6 to one ability check, attack roll, or saving throw in the next minute. You can use this a number of times equal to your Charisma modifier per long rest." },
      ],
      3: [{ name: "Suit Archetype", description: "You choose a suit archetype: Commander (tactical military officer and squad leader), G-Man (federal agent with investigative and enforcement powers), or Shark (corporate operative with hacking access — gains 1/3 suit levels in hack slots). Your archetype grants features at 3rd, 6th, 10th, and 14th level." }, { name: "Expertise", description: "Choose two of your skill proficiencies. Your proficiency bonus is doubled for ability checks using those skills." }],
      4: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      5: [{ name: "Inspire (d8)", description: "Your Inspire Allies die becomes a d8." }, { name: "Font of Inspiration", description: "You regain all expended Inspire uses when you finish a short or long rest." }],
      6: [{ name: "Archetype Feature", description: "You gain a feature from your suit archetype." }],
      7: [{ name: "Counterplay", description: "You can use your reaction to impose disadvantage on a Charisma check made against you or an ally within 9 meters." }],
      8: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      9: [{ name: "Leverage", description: "Once per short rest, you can claim leverage over a creature you have interacted with, giving you advantage on all Charisma checks against that creature for 24 hours." }],
      10: [{ name: "Archetype Feature", description: "You gain a feature from your suit archetype." }, { name: "Expertise (2)", description: "Choose two more skill proficiencies to gain expertise in." }],
      11: [{ name: "Inspire (d10)", description: "Your Inspire Allies die becomes a d10." }],
      12: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      13: [{ name: "Power Broker", description: "You can spend 24 hours gathering information to gain a detailed dossier on any named individual: their weaknesses, alliances, assets, and secrets." }],
      14: [{ name: "Archetype Feature", description: "You gain a feature from your suit archetype." }],
      15: [{ name: "Inspire (d12)", description: "Your Inspire Allies die becomes a d12." }],
      16: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      17: [{ name: "Master Negotiator", description: "You have advantage on all Charisma checks. Creatures cannot be immune to your Persuasion checks unless they are constructs or undead." }],
      18: [{ name: "The Closer", description: "Once per long rest, you automatically succeed on a Charisma check. Alternatively, you can force one creature to reroll a Charisma saving throw against one of your effects and take the lower result." }],
      19: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above 20." }],
      20: [{ name: "Shadow Cabinet", description: "Your network of contacts is vast and elite. You can call in a favor from the most powerful entities in the world — megacorporation executives, government ministers, or cartel bosses — once per long rest." }],
    },
  },
];

export const BACKGROUNDS: BackgroundData[] = [
  {
    name: "Corporate Agent",
    description: "You served one of the megacorporations that dominate the world of 2090, working as an operative, analyst, or enforcer.",
    skillProficiencies: ["bureaucracy", "persuasion"],
    featureName: "Corporate Connections",
    featureDescription: "You have contacts within corporate networks. You can leverage these connections to gain access to corporate facilities, information, or resources.",
    toolProficiencies: "One type of gaming set",
    languages: "One language of your choice",
  },
  {
    name: "Street Rat",
    description: "You grew up on the streets, learning to survive through wit, cunning, and a healthy dose of paranoia.",
    skillProficiencies: ["stealth", "streetwise"],
    featureName: "Street Cred",
    featureDescription: "You are known in the underground. You can find safe houses, fences for stolen goods, and information brokers in any urban area.",
    toolProficiencies: "Thieves' tools",
  },
  {
    name: "Military Veteran",
    description: "You served in one of the world's military forces, gaining discipline, combat training, and the scars that come with it.",
    skillProficiencies: ["athletics", "intimidation"],
    featureName: "Military Rank",
    featureDescription: "You still carry your rank and can invoke it to gain cooperation from soldiers and veterans. You can also access military installations with proper identification.",
    toolProficiencies: "Vehicles (Land)",
    languages: "One language of your choice",
  },
  {
    name: "Academic",
    description: "You spent years in academic institutions, researching the cutting edge of science and technology.",
    skillProficiencies: ["investigation", "lifeScience"],
    featureName: "Researcher",
    featureDescription: "When you attempt to learn or recall information, if you don't know it, you know where and from whom you can obtain it.",
    languages: "Two languages of your choice",
  },
  {
    name: "Criminal",
    description: "You have a history of breaking the law. You might have been a smuggler, burglar, or enforcer for a criminal syndicate.",
    skillProficiencies: ["deception", "stealth"],
    featureName: "Criminal Contact",
    featureDescription: "You have a reliable and trustworthy contact who acts as your liaison to a network of other criminals.",
    toolProficiencies: "Thieves' tools, one type of gaming set",
  },
  {
    name: "Medtech",
    description: "You trained in medicine and biotechnology, working in hospitals, clinics, or field medical units.",
    skillProficiencies: ["lifeScience", "perception"],
    featureName: "Medical License",
    featureDescription: "You can practice medicine legally and have access to medical supplies at reduced cost. Medical facilities are more likely to cooperate with you.",
    toolProficiencies: "Medical kit, Herbalism kit",
  },
  {
    name: "Fixer",
    description: "You are a dealmaker and information broker, connecting people who need things with people who have things.",
    skillProficiencies: ["insight", "persuasion"],
    featureName: "Contact Network",
    featureDescription: "You maintain an extensive network of contacts across various walks of life. You can find buyers, sellers, and specialists for almost any need.",
    toolProficiencies: "Forgery kit",
    languages: "Two languages of your choice",
  },
  {
    name: "Nomad",
    description: "You lived outside the megacities, traveling the wastes and wilderlands between the urban sprawls.",
    skillProficiencies: ["survival", "drive"],
    featureName: "Wanderer",
    featureDescription: "You have an excellent memory for maps and geography. You can always recall the general layout of terrain, settlements, and other features around you.",
    toolProficiencies: "Vehicles (Land)",
    languages: "One language of your choice",
  },
  {
    name: "Hacker Underground",
    description: "You were part of the digital underground, hacking systems and fighting for data freedom.",
    skillProficiencies: ["computers", "investigation"],
    featureName: "Backdoor Access",
    featureDescription: "You know hidden entry points in common computer systems and networks. You have advantage on the first Computers check you make when attempting to access a new system.",
    toolProficiencies: "Hacking tools",
  },
  {
    name: "Entertainer",
    description: "You made your living performing for others — music, acting, street performance, or digital content creation.",
    skillProficiencies: ["performance", "acrobatics"],
    featureName: "By Popular Demand",
    featureDescription: "You can always find a place to perform. You receive free lodging and food in exchange for performing. Your performances make you something of a local figure.",
    toolProficiencies: "One musical instrument, Disguise kit",
  },
];

export const POINT_BUY_COSTS: Record<number, number> = {
  8: 0,
  9: 1,
  10: 2,
  11: 3,
  12: 4,
  13: 5,
  14: 7,
  15: 9,
};

export const POINT_BUY_TOTAL = 27;
