import type { InsertCharacter } from "../schema/characters";

export function createEstebanSeedData(userId: string): InsertCharacter {
  return {
    userId,
    name: "Esteban",
    cadre: "ESPION",
    class: "Monk",
    level: 5,
    strength: 10,
    dexterity: 18,
    constitution: 14,
    intelligence: 8,
    wisdom: 16,
    charisma: 12,
    maxHitPoints: 48,
    currentHitPoints: 48,
    temporaryHitPoints: 0,
    armorClass: 17,
    initiative: 4,
    speed: 40,
    proficiencyBonusOverride: 3,
    savingThrowProficiencies: ["strength", "dexterity"],
    skillProficiencies: [
      "acrobatics",
      "athletics",
      "perception",
      "performance",
      "persuasion",
      "drive",
      "bureaucracy",
    ],
    passivePerception: 16,
    weaponProficiencies: "Crossbow (Hand), Scimitar, Shortsword, Simple Weapons",
    toolProficiencies: "Alchemist's Supplies, Vehicles (Land)",
    languages: "Abyssal, Common",
    attacks: [
      {
        id: "esteban-atk-1",
        name: "Nanoedge Cane Sword",
        attackBonus: "+7",
        damage: "1d8+4",
        damageType: "slashing",
        range: "5 ft",
        notes: null,
        weaponType: "martial_melee",
        isFinesse: false,
      },
      {
        id: "esteban-atk-2",
        name: "Nanoedge Kerambit",
        attackBonus: "+7",
        damage: "1d8+8",
        damageType: "slashing",
        range: "20/60",
        notes: "Thrown",
        weaponType: "martial_melee",
        isFinesse: false,
      },
      {
        id: "esteban-atk-3",
        name: "Unarmed Strike",
        attackBonus: "+7",
        damage: "1d8+4",
        damageType: "bludgeoning",
        range: "5 ft",
        notes: null,
        weaponType: "simple_melee",
        isFinesse: false,
      },
    ],
    hitDice: "5d8",
  };
}
