import type { AbilityKey } from './types';

export interface ClassData {
  name: string;
  hitDie: number;
  savingThrows: AbilityKey[];
  armorProficiencies: string;
  weaponProficiencies: string;
  skillChoices: string[];
  numSkillChoices: number;
  mandatorySkills?: string[];
  featuresByLevel: Record<number, { name: string; description: string }[]>;
}


export const CLASSES: ClassData[] = [
  {
    name: "Biohacker",
    hitDie: 8,
    savingThrows: ["intelligence", "dexterity"],
    armorProficiencies: "Light armor",
    weaponProficiencies: "Simple weapons",
    skillChoices: ["bureaucracy", "computers", "deception", "drive", "insight", "investigation", "physicalScience", "mechanics", "socialScience", "survival"],
    numSkillChoices: 2,
    mandatorySkills: ["lifeScience"],
    featuresByLevel: {
      1: [
        { name: "Hacking", description: "You are able to use hacks that alter physiology and anatomy the way a potter molds clay. Intelligence is your hacking ability. Hack save DC = 8 + proficiency bonus + Intelligence modifier. You start knowing three 1st-level hacks of your choice from the Biohacker hack list, as well as the nanodoc and forensic scan hacks. You regain all expended hack slots when you finish a long rest." },
        { name: "Life Scientist", description: "You gain expertise in Life Science — your proficiency bonus is doubled for any ability check you make using this skill. Additionally, forensic scan can be run without expending a hack slot as long as you choose to take 10 minutes longer to run it than normal." },
      ],
      2: [{ name: "Conscientious Focus", description: "You've trained your mind to be especially disciplined. This enables you to run an additional hack or upgrade that requires concentration (you may concentrate on one more effect than normal). This feature stacks with any other ability or implant that allows you to concentrate on additional hacks or upgrades." }],
      3: [{ name: "Biotic Aptitude", description: "The Biotic Aptitude you choose reflects your approach to biohacking. It grants you features at 3rd level and then again at 6th, 10th, 14th, and 17th level. Subtypes: Cytomancer (cellular manipulation and healing), Dr. Frankenstein (reanimation and construct enhancement), Protean Grinder (adaptive genetic mutation)." }],
      4: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      5: [{ name: "Biohacker Contact", description: "You gain a contact with ties to the medical or biohacker community — an EMT, doctor, nurse, biologist, geneticist, bioengineer, or similar. You get an additional contact at levels 13 and 18." }],
      6: [{ name: "Biotic Aptitude Feature", description: "You gain a feature from your Biotic Aptitude archetype." }],
      7: [{ name: "Bioware Upgrade", description: "You acquire an upgrade from Chapter 5: Upgrades through your connection to illicit circles, so you can get upgrades that are restricted or banned. At 7th level you may select an upgrade worth up to シ50,000." }],
      8: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      9: [{ name: "Surgical Strikes", description: "Your knowledge of anatomy and physiology allows you to strike with surgical precision on vital organs. Once on each of your turns when you hit with a weapon attack, you can cause the attack to deal an extra 1d8 damage of the same type dealt by the weapon. When you reach 15th level, the extra damage increases to 2d8." }],
      10: [{ name: "Biotic Aptitude Feature", description: "You gain a feature from your Biotic Aptitude archetype." }],
      11: [{ name: "Bioware Upgrade", description: "You gain an additional upgrade. At 11th level you may select an upgrade worth up to シ100,000. Additionally, you can replace one upgrade you already have with another of equal or lesser value." }],
      12: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      13: [{ name: "Biohacker Contact (2nd)", description: "You gain your second contact with ties to the medical or biohacker community." }],
      14: [{ name: "Biotic Aptitude Feature", description: "You gain a feature from your Biotic Aptitude archetype. Also, at 14th level you may select a Bioware Upgrade worth up to シ200,000." }],
      15: [{ name: "Bioware Upgrade", description: "You gain an additional upgrade. At 15th level you may select an upgrade worth up to シ200,000." }],
      16: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      17: [{ name: "Biotic Aptitude Feature", description: "You gain a feature from your Biotic Aptitude archetype." }],
      18: [{ name: "Bioware Upgrade (any)", description: "You gain an additional upgrade and may select any upgrade regardless of cost. Additionally, you gain your 3rd Biohacker Contact." }],
      19: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      20: [{ name: "Double Helix Guru", description: "You have achieved such mastery over certain hacks that you can run them with ease. Choose two 1st-level and one 2nd-level hacks that you know. You can run those hacks at their lowest level without expending a hack slot." }],
    },
  },
  {
    name: "Codehacker",
    hitDie: 8,
    savingThrows: ["intelligence", "wisdom"],
    armorProficiencies: "Light armor",
    weaponProficiencies: "Simple weapons",
    skillChoices: ["bureaucracy", "deception", "drive", "investigation", "lifeScience", "mechanics", "physicalScience", "socialScience", "stealth"],
    numSkillChoices: 2,
    mandatorySkills: ["computers"],
    featuresByLevel: {
      1: [
        { name: "Adept Coder", description: "You gain expertise in Computers — your proficiency bonus is doubled for any ability check you make using this skill." },
        { name: "Dataport", description: "You start with a dataport upgrade, and can hook up your daemon directly to other devices that have jacks without using wireless. This bypasses attempts to jam or detect wireless signals and is essential to interface with CCTV and sensitive databases that lack wireless capability." },
        { name: "Hacking", description: "You are able to use hacks to cut through anything that has a computer inside, which is pretty much everything, including human minds. Intelligence is your hacking ability. Hack save DC = 8 + proficiency bonus + Intelligence modifier. You start knowing three 1st-level hacks of your choice, as well as the decrypt and unlock hacks. You regain all expended hack slots when you finish a long rest." },
      ],
      2: [
        { name: "Custom OS", description: "You've custom made your own OS, and it runs incredibly efficiently. This enables you to run an additional program or upgrade that requires concentration (you may concentrate on one more effect than normal). This feature stacks with any other ability or implant that allows you to concentrate on additional hacks or upgrades." },
        { name: "Traumatize", description: "You developed a technique to inflict confusion, pain, and psychic trauma on an individual. As an action, target an enemy within 36 meters that you can see. They must make a Wisdom saving throw, and if they fail, they take 1d12 psychic damage. This damage increases to 2d12 at level 6, 3d12 at level 11, and 4d12 at level 17. This feature is considered a mind hack." },
      ],
      3: [{ name: "Hacker Archetype", description: "The hacker archetype you choose reflects your approach to hacking. Your hacker archetype choice grants you features at 3rd level and then again at 6th, 10th, 14th, 17th, and 18th level. Subtypes: Cracker (breaking through digital security), Puppeteer (controlling minds and systems), Synergist (linking minds into a combat network)." }],
      4: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      5: [{ name: "Cyber Contact", description: "You gain a contact with ties to the hacker community — a government white-hat, criminal cracker, Silicon Valley coder, basement troll, or any other hacker. You get an additional contact at levels 9, 13, and 18." }],
      6: [{ name: "Archetype Feature", description: "You gain a feature from your Hacker Archetype." }],
      7: [{ name: "Pirate Upgrade", description: "You acquire an upgrade from Chapter 5: Upgrades through your connection to pirate hacker circles, so you can get upgrades that are restricted or banned. At 7th level you may select an upgrade worth up to シ50,000." }],
      8: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      9: [
        { name: "Cyber Contact (2nd)", description: "You gain your second contact with ties to the hacker community." },
        { name: "Targeting Firmware", description: "You've developed firmware that optimizes your hand-eye coordination when aiming and firing. You gain a damage bonus to all damage rolls equal to your Intelligence modifier." },
      ],
      10: [{ name: "Archetype Feature", description: "You gain a feature from your Hacker Archetype." }],
      11: [{ name: "Pirate Upgrade", description: "You gain an additional upgrade. At 11th level you may select an upgrade worth up to シ100,000. Additionally, you can replace one upgrade you already have with another of equal or lesser value." }],
      12: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      13: [{ name: "Cyber Contact (3rd)", description: "You gain your third contact with ties to the hacker community." }],
      14: [{ name: "Archetype Feature", description: "You gain a feature from your Hacker Archetype." }],
      15: [{ name: "Pirate Upgrade", description: "You gain an additional upgrade and may replace one you already have with a more expensive one." }],
      16: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      17: [{ name: "Archetype Feature", description: "You gain a feature from your Hacker Archetype." }],
      18: [{ name: "Pirate Upgrade (any)", description: "You gain an additional upgrade and may select any upgrade regardless of cost. Additionally, you gain your 4th Cyber Contact." }],
      19: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      20: [{ name: "Codemaster", description: "You have achieved such mastery over certain hacks that you can run them with ease. Choose two 1st-level and one 2nd-level hacks that you know. You can run those hacks at their lowest level without expending a hack slot." }],
    },
  },
  {
    name: "Crook",
    hitDie: 8,
    savingThrows: ["dexterity", "intelligence"],
    armorProficiencies: "Light armor",
    weaponProficiencies: "Simple weapons",
    skillChoices: ["acrobatics", "athletics", "bureaucracy", "computers", "deception", "drive", "insight", "intimidation", "investigation", "mechanics", "perception", "performance", "persuasion", "sleightOfHand", "stealth", "streetwise"],
    numSkillChoices: 4,
    featuresByLevel: {
      1: [
        { name: "Expertise", description: "Choose two of your skill proficiencies. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies." },
        { name: "Sneak Attack", description: "Once per turn you can deal extra damage to one creature you hit with a finesse or ranged weapon if you have advantage on the attack roll. The extra damage is 1d6, and increases as you gain crook levels: 2d6 at 3rd, 3d6 at 5th, 4d6 at 7th, 5d6 at 9th, 6d6 at 11th, 7d6 at 13th, 8d6 at 15th, 9d6 at 17th, 10d6 at 19th. You don't need advantage if another enemy of the target is within 1.5 meters of it." },
      ],
      2: [{ name: "Cunning Action", description: "You can use a bonus action to take the Dash, Disengage, or Hide action." }],
      3: [
        { name: "Crooked Path", description: "You choose a criminal archetype that grants you features at 3rd level and then again at 9th, 13th, and 17th level. Subtypes: Hitman (contract killer and assassin — Assassinate, Prey Dossier), Robber (safecracker and burglar — Pickpocket, Safecracker)." },
        { name: "Shady Contact", description: "You gain a contact with ties to the criminal underworld. You get an additional contact at levels 7, 11, 15, and 18." },
      ],
      4: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      5: [{ name: "Illicit Upgrade", description: "You acquire an upgrade from Chapter 5: Upgrades through your criminal connections, so you can get upgrades that are restricted or banned. You gain additional upgrades at levels 7, 11, 14, and 18." }],
      6: [{ name: "Uncanny Dodge", description: "When an attacker that you can see hits you with an attack, you can use your reaction to halve the attack's damage against you." }],
      7: [
        { name: "Illicit Upgrade", description: "You gain an additional upgrade through your criminal connections." },
        { name: "Shady Contact (2nd)", description: "You gain your second contact with ties to the criminal underworld." },
      ],
      8: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      9: [{ name: "Crooked Path Feature", description: "You gain a feature from your Crooked Path archetype." }],
      10: [
        { name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." },
        { name: "Safe House", description: "You have a safe house — a hideout known only to you and your most trusted allies. Work with your GM to determine its location and what it contains. It provides a secure place to rest, store contraband, and lay low." },
      ],
      11: [
        { name: "Illicit Upgrade", description: "You gain an additional upgrade through your criminal connections." },
        { name: "Shady Contact (3rd)", description: "You gain your third contact with ties to the criminal underworld." },
      ],
      12: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      13: [{ name: "Crooked Path Feature", description: "You gain a feature from your Crooked Path archetype." }],
      14: [{ name: "Illicit Upgrade", description: "You gain an additional upgrade through your criminal connections." }],
      15: [{ name: "Shady Contact (4th)", description: "You gain your fourth contact with ties to the criminal underworld." }],
      16: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      17: [{ name: "Crooked Path Feature", description: "You gain a feature from your Crooked Path archetype." }],
      18: [
        { name: "Illicit Upgrade", description: "You gain an additional upgrade through your criminal connections." },
        { name: "Shady Contact (5th)", description: "You gain your fifth contact with ties to the criminal underworld." },
      ],
      19: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      20: [{ name: "Infamous", description: "Your reputation in the criminal underworld is legendary. Criminals everywhere know your name. You have advantage on all Intimidation and Persuasion checks against members of criminal organizations. Additionally, you can add your proficiency bonus to your Sneak Attack damage once per turn as a flat bonus." }],
    },
  },
  {
    name: "Engineer",
    hitDie: 8,
    savingThrows: ["constitution", "intelligence"],
    armorProficiencies: "Light armor",
    weaponProficiencies: "Simple weapons",
    skillChoices: ["bureaucracy", "computers", "deception", "drive", "investigation", "lifeScience", "physicalScience", "socialScience", "stealth"],
    numSkillChoices: 2,
    mandatorySkills: ["mechanics"],
    featuresByLevel: {
      1: [
        { name: "Hacking", description: "You are able to use hacks to modify, create, and enhance technology. Intelligence is your hacking ability. Hack save DC = 8 + proficiency bonus + Intelligence modifier. You start knowing three 1st-level hacks of your choice from the engineer hack list, as well as the arc drone and tase hacks. You regain all expended hack slots when you finish a long rest." },
        { name: "Technical Expertise", description: "You gain expertise in Mechanics — your proficiency bonus is doubled for any ability check you make that uses this proficiency." },
      ],
      2: [{ name: "Construct Gear", description: "You can fabricate your own devices and gadgets, either repairing second-hand stuff or making it from scratch. Instead of buying any gear item, you can make it yourself paying only half the money. This takes 1 hour per シ1,000 in listed price (minimum 1 hour), and the listed price may not exceed シ5,000 x your engineer level. Cannot be used for weapons or armor. Each time you use crafted DIY gear, roll 1d20 — on a 1, it malfunctions for 1 minute." }],
      3: [{ name: "Engineer Archetype", description: "The engineer archetype you choose reflects your approach to engineering. It grants features at 3rd level and then again at 6th, 10th, 14th, and 17th level. Subtypes: Gadgeteer (experimental device crafter), Gearhead (vehicle and mechanical expert), Roboticist (combat drone and synthetic companion builder)." }],
      4: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      5: [{ name: "Builder Contact", description: "You gain a contact with ties to the engineering and manufacturing world. You get an additional contact at levels 13 and 18." }],
      6: [{ name: "Archetype Feature", description: "You gain a feature from your Engineer Archetype." }],
      7: [{ name: "Tech Upgrade", description: "You acquire an upgrade from Chapter 5: Upgrades through your connections to engineering and manufacturing. At 7th level you may select an upgrade worth up to シ50,000." }],
      8: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      9: [{ name: "Structural Exploit", description: "You have learned to exploit structural weaknesses in technology and machinery. When you hit a droid, drone, or vehicle with a weapon attack, you can deal additional damage equal to your Intelligence modifier." }],
      10: [{ name: "Archetype Feature", description: "You gain a feature from your Engineer Archetype." }],
      11: [{ name: "Tech Upgrade", description: "You gain an additional upgrade. At 11th level you may select an upgrade worth up to シ100,000. Additionally, you can replace one upgrade you already have with another of equal or lesser value." }],
      12: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      13: [{ name: "Builder Contact (2nd)", description: "You gain your second contact with ties to the engineering and manufacturing world." }],
      14: [{ name: "Archetype Feature", description: "You gain a feature from your Engineer Archetype. Also, at 14th level you may select a Tech Upgrade worth up to シ200,000." }],
      15: [{ name: "Tech Upgrade", description: "You gain an additional upgrade worth up to シ200,000." }],
      16: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      17: [{ name: "Archetype Feature", description: "You gain a feature from your Engineer Archetype." }],
      18: [{ name: "Tech Upgrade (any)", description: "You gain an additional upgrade and may select any upgrade regardless of cost. Additionally, you gain your 3rd Builder Contact." }],
      19: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      20: [{ name: "Patented Hacks", description: "You have achieved such mastery over certain hacks that you can run them with ease. Choose two 1st-level and one 2nd-level hacks that you know. You can run those hacks at their lowest level without expending a hack slot." }],
    },
  },
  {
    name: "Gunfighter",
    hitDie: 10,
    savingThrows: ["dexterity", "constitution"],
    armorProficiencies: "All armor",
    weaponProficiencies: "Simple weapons, martial ranged weapons",
    skillChoices: ["acrobatics", "athletics", "computers", "drive", "insight", "intimidation", "mechanics", "perception", "stealth", "streetwise", "survival"],
    numSkillChoices: 2,
    featuresByLevel: {
      1: [
        { name: "Fighting Style", description: "You adopt a particular style of fighting as your specialty. Choose one: Marksman (+2 bonus to attack rolls with ranged weapons), Defense (+1 bonus to AC while wearing armor), Machine Gunner (reduce recoil by 3 when using the auto feature of a firearm), Pistoleer (+2 bonus to damage rolls with firearms with the 'close' property). You can't take the same Fighting Style more than once." },
        { name: "Take Cover", description: "When you are hit by a ranged attack, you can use your reaction to dive for cover, reducing the damage taken. You have one use of this feature. You gain additional uses at 11th level (two uses) and 20th level (three uses)." },
      ],
      2: [{ name: "Action Surge", description: "On your turn, you can take one additional action. Once you use this feature, you must finish a short or long rest before you can use it again. You gain two uses at 13th level and three uses at 20th level." }],
      3: [{ name: "Way of the Gun", description: "The way of the gun you choose reflects your approach to firearms combat. It grants you features at 3rd level and then again at 7th, 10th, 15th, and 18th level. Subtypes: Gunslinger (quick-draw pistol specialist — Improved Handgun Critical, Quickdraw), Sniper (long-range precision — Deadly Aim, targeting body parts), Soldier (military tactics and upgrades — Soldier Military Upgrade, Armored Comfort)." }],
      4: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      5: [{ name: "Extra Attack", description: "You can attack twice, instead of once, whenever you take the Attack action on your turn." }],
      6: [{ name: "Military Upgrade", description: "You acquire an upgrade from Chapter 5: Upgrades through military connections. At 6th level you may select an upgrade worth up to シ30,000." }],
      7: [
        { name: "Way of the Gun Feature", description: "You gain a feature from your Way of the Gun archetype." },
        { name: "Military Contact", description: "You gain a contact with ties to military or law enforcement. You get an additional contact at 13th level." },
      ],
      8: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      9: [
        { name: "Military Upgrade", description: "You gain an additional Military Upgrade worth up to シ75,000." },
        { name: "Evasion", description: "You can nimbly dodge out of the way of certain area effects, such as a grenade blast. When you are subjected to an effect that allows you to make a Dexterity saving throw to take only half damage, you instead take no damage if you succeed on the saving throw, and only half damage if you fail." },
      ],
      10: [{ name: "Way of the Gun Feature", description: "You gain a feature from your Way of the Gun archetype." }],
      11: [
        { name: "Military Upgrade", description: "You gain an additional Military Upgrade worth up to シ100,000." },
        { name: "Take Cover (two uses)", description: "You can now use your Take Cover feature twice per encounter." },
      ],
      12: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      13: [
        { name: "Action Surge (two uses)", description: "You can now use Action Surge twice before a rest." },
        { name: "Military Contact (2nd)", description: "You gain your second Military Contact." },
      ],
      14: [
        { name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." },
        { name: "Military Upgrade", description: "You gain an additional Military Upgrade worth up to シ200,000." },
      ],
      15: [{ name: "Way of the Gun Feature", description: "You gain a feature from your Way of the Gun archetype." }],
      16: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      17: [{ name: "Military Upgrade (any)", description: "You gain an additional Military Upgrade and may select any upgrade regardless of cost." }],
      18: [{ name: "Way of the Gun Feature", description: "You gain a feature from your Way of the Gun archetype." }],
      19: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      20: [
        { name: "Action Surge (three uses)", description: "You can now use Action Surge three times before a rest." },
        { name: "Take Cover (three uses)", description: "You can now use your Take Cover feature three times per encounter." },
      ],
    },
  },
  {
    name: "Hardcase",
    hitDie: 12,
    savingThrows: ["strength", "constitution"],
    armorProficiencies: "Light armor, medium armor",
    weaponProficiencies: "Simple weapons",
    skillChoices: ["acrobatics", "athletics", "drive", "insight", "intimidation", "perception", "sleightOfHand", "stealth", "streetwise"],
    numSkillChoices: 2,
    featuresByLevel: {
      1: [
        { name: "Unarmored Defense", description: "While you are not wearing any armor, your Armor Class equals 10 + your Dexterity modifier + your Constitution modifier." },
        { name: "Second Wind", description: "On your turn, you can use a bonus action to regain hit points equal to 1d10 + your hardcase level. Once you use this feature, you must finish a short or long rest before you can use it again. You gain 2 uses at 10th level and 3 uses at 15th level." },
        { name: "Pugilist", description: "You are trained in unarmed combat. You can make one unarmed strike or initiate a grapple as a bonus action. Your unarmed strikes deal increased damage as shown on the Hardcase table (1d4 at levels 1–4, 1d6 at 5–8, 1d8 at 9–12, 1d10 at 13–16, 1d12 at 17–20). You can also use your action to attempt to pin a grappled creature." },
        { name: "Brutal Focus (d4)", description: "As a bonus action, you can choose a target you can see within 18 meters and single it out as the total focus of your violent tendencies. You deal an extra 1d4 damage to the target whenever you hit it with a weapon attack. This ability requires concentration. All of your attacks must be directed toward the Brutal Focus target while this is active." },
      ],
      2: [{ name: "Fighting Style", description: "You adopt a particular style of fighting as your specialty. Choose one Fighting Style. You can't take the same Fighting Style option more than once." }],
      3: [{ name: "Brute Specialty", description: "You choose a specialty that reflects your fighting approach. It grants features at 3rd level and then again at 7th, 9th, and 14th level. Subtypes: Damage Sponge (unstoppable tank), Gangster (street enforcer with criminal connections), Unarmed Fighter (bare-knuckle brawler)." }],
      4: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      5: [{ name: "Extra Attack", description: "You can attack twice, instead of once, whenever you take the Attack action on your turn." }],
      6: [
        { name: "Shady Contact", description: "You gain a contact with ties to the criminal underworld. You get an additional contact at levels 13 and 17." },
        { name: "Heavy Hands", description: "When you score a critical hit with an unarmed strike, the target is knocked prone." },
        { name: "Brutal Focus (d6)", description: "Your Brutal Focus bonus damage increases to 1d6." },
      ],
      7: [
        { name: "Illicit Upgrade", description: "You acquire an upgrade from Chapter 5: Upgrades through your criminal connections. At 7th level you may select an upgrade worth up to シ50,000." },
        { name: "Specialty Feature", description: "You gain a feature from your Brute Specialty." },
      ],
      8: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      9: [
        { name: "Indomitable", description: "You can reroll a saving throw that you fail. If you do so, you must use the new roll. You can use this feature once between long rests. You gain 2 uses at 13th level and 3 uses at 17th level." },
        { name: "Specialty Feature", description: "You gain a feature from your Brute Specialty." },
      ],
      10: [
        { name: "Relentless Stamina", description: "When you are reduced to 0 hit points but not killed outright, you can make a DC 10 Constitution saving throw. On a success, you drop to 1 hit point instead. Each time you use this feature after the first, the DC increases by 5. The DC resets when you finish a long rest." },
        { name: "Second Wind (2 uses)", description: "You can now use Second Wind twice per short or long rest." },
      ],
      11: [
        { name: "Illicit Upgrade", description: "You gain an additional upgrade through your criminal connections worth up to シ100,000." },
        { name: "Scary", description: "As an action, you can attempt to frighten a creature within 9 meters. The creature must make a Wisdom saving throw against DC 8 + your proficiency bonus + your Strength modifier or become frightened of you for 1 minute." },
        { name: "Brutal Focus (d8)", description: "Your Brutal Focus bonus damage increases to 1d8." },
      ],
      12: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      13: [
        { name: "Indomitable (2 uses)", description: "You can now use Indomitable twice between long rests." },
        { name: "Shady Contact (2nd)", description: "You gain your second contact with ties to the criminal underworld." },
      ],
      14: [{ name: "Specialty Feature", description: "You gain a feature from your Brute Specialty." }],
      15: [
        { name: "Second Wind (3 uses)", description: "You can now use Second Wind three times per short or long rest." },
        { name: "Illicit Upgrade", description: "You gain an additional upgrade through your criminal connections worth up to シ200,000." },
      ],
      16: [
        { name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." },
        { name: "Brutal Focus (d10)", description: "Your Brutal Focus bonus damage increases to 1d10." },
      ],
      17: [
        { name: "Indomitable (3 uses)", description: "You can now use Indomitable three times between long rests." },
        { name: "Shady Contact (3rd)", description: "You gain your third contact with ties to the criminal underworld." },
      ],
      18: [
        { name: "Unwavering Might", description: "You are nearly impossible to stop. You have advantage on saving throws against being frightened or charmed. Additionally, when you are grappled or restrained, you can use your bonus action to attempt to break free." },
        { name: "Illicit Upgrade (any)", description: "You gain an additional upgrade through your criminal connections and may select any upgrade regardless of cost." },
      ],
      19: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      20: [
        { name: "Rampage", description: "When your Brutal Focus is active, all of your hits against the target of your Brutal Focus are automatically critical hits. Additionally, you add +5 to all Relentless Stamina Constitution saving throws." },
        { name: "Brutal Focus (d12)", description: "Your Brutal Focus bonus damage increases to 1d12." },
      ],
    },
  },
  {
    name: "Samurai",
    hitDie: 10,
    savingThrows: ["strength", "dexterity"],
    armorProficiencies: "Light armor, medium armor",
    weaponProficiencies: "Simple weapons, martial melee weapons",
    skillChoices: ["acrobatics", "athletics", "drive", "insight", "intimidation", "investigation", "perception", "socialScience", "stealth", "streetwise"],
    numSkillChoices: 3,
    featuresByLevel: {
      1: [
        { name: "Unarmored Defense", description: "Starting at 1st level, while you are not wearing any armor, your Armor Class equals 10 + your Dexterity modifier + your Wisdom modifier." },
        { name: "Martial Arts", description: "Your practice of martial arts gives you mastery of combat styles that use unarmed strikes and melee attacks while unarmored or wearing light or medium armor. You can use Dexterity instead of Strength for the attack rolls of your unarmed strikes. Your unarmed strikes inflict increased damage as shown on the Samurai table (1d4 at 1–4, 1d6 at 5–8, 1d8 at 9–12, 1d10 at 13–16, 1d12 at 17–20). You can make an unarmed strike or initiate a grapple as a bonus action, and you can use your action or bonus action to try to pin a grappled creature." },
        { name: "Ki", description: "Your training allows you to harness ki energy. Your samurai level determines the number of ki points you have (1 at level 1, increasing by 1 each level). You regain all spent ki at the end of a short or long rest (you must spend at least 30 minutes meditating). Ki save DC = 8 + proficiency bonus + Wisdom modifier. Starting features: Flurry of Blows (spend 1 ki after Attack action to make two unarmed strikes as bonus action), Patient Defense (spend 1 ki to Dodge as bonus action), Step of the Wind (spend 1 ki to Disengage or Dash as bonus action, jump distance doubled)." },
      ],
      2: [{ name: "Fighting Style", description: "At level 2, you adopt a particular style of fighting as your specialty. Choose one Fighting Style. You can't take the same Fighting Style option more than once." }],
      3: [{ name: "Bujutsu Training", description: "You choose a Bujutsu Training archetype and also learn one technique from the Bujutsu Training list. You gain additional techniques at levels 6, 9, 13, 15, 17, and 20. Each time you get a new Bujutsu Training, you may also replace one technique you know with a different one." }],
      4: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      5: [
        { name: "Extra Attack", description: "Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn. At 20th level, you can attack three times." },
        { name: "Senshi Upgrade", description: "You acquire an upgrade from Chapter 5: Upgrades through your connections to either private, municipal, or national military forces. At 5th level you may select an upgrade worth up to シ25,000." },
      ],
      6: [{ name: "Bujutsu Training", description: "You learn an additional technique from the Bujutsu Training list." }],
      7: [
        { name: "Senshi Upgrade", description: "You gain an additional Senshi Upgrade worth up to シ50,000." },
        { name: "Samurai Contact", description: "You gain a contact that has gone through the Bushido training academy — a samurai working for Bushido as a mercenary, instructor, or administrator, or a free-lance samurai. You get an additional contact at level 14." },
      ],
      8: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      9: [{ name: "Bujutsu Training", description: "You learn an additional technique from the Bujutsu Training list." }],
      10: [{ name: "Calm the Hungry Ghost", description: "By 10th level, you have reduced the nagging effect of your ego, recognizing its emptiness. You gain proficiency in Charisma saving throws." }],
      11: [{ name: "Senshi Upgrade", description: "You gain an additional Senshi Upgrade worth up to シ100,000. Additionally, you can replace one upgrade you already have with another of equal or lesser value." }],
      12: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      13: [{ name: "Bujutsu Training", description: "You learn an additional technique from the Bujutsu Training list." }],
      14: [
        { name: "Senshi Upgrade", description: "You gain an additional Senshi Upgrade worth up to シ200,000." },
        { name: "Samurai Contact (2nd)", description: "You gain your second Samurai Contact." },
      ],
      15: [{ name: "Bujutsu Training", description: "You learn an additional technique from the Bujutsu Training list." }],
      16: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      17: [{ name: "Bujutsu Training", description: "You learn an additional technique from the Bujutsu Training list." }],
      18: [{ name: "Senshi Upgrade (any)", description: "You gain an additional Senshi Upgrade and may select any upgrade regardless of cost." }],
      19: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      20: [
        { name: "Extra Attack (2)", description: "You can now attack three times whenever you take the Attack action on your turn." },
        { name: "Bujutsu Training", description: "You learn an additional technique from the Bujutsu Training list." },
      ],
    },
  },
  {
    name: "Suit",
    hitDie: 8,
    savingThrows: ["wisdom", "charisma"],
    armorProficiencies: "Light armor",
    weaponProficiencies: "Simple weapons",
    skillChoices: ["acrobatics", "athletics", "bureaucracy", "computers", "deception", "drive", "insight", "intimidation", "investigation", "lifeScience", "mechanics", "perception", "performance", "persuasion", "socialScience", "stealth"],
    numSkillChoices: 4,
    featuresByLevel: {
      1: [
        { name: "Inspiration (d6)", description: "You can inspire others through your words and presence. As a bonus action, you can choose one creature other than yourself within 18 meters that can hear you. That creature gains an Inspiration die (d6). Once within the next 10 minutes, the creature can roll the die and add the result to one ability check, attack roll, or saving throw. The Inspiration die increases to d8 at 5th level, d10 at 11th level, and d12 at 15th level." },
        { name: "Power Network", description: "Suits are always backed by a powerful organization. At level 1, decide which power network you associate with and have power in: a government or military agency (FBI, CIA, NSA, INTERPOL, etc.), a major megacorporation (Apex International, Apollo Laboratories, Ronin, Cornucopia, Worldgroup Holdings, Infinity Industries, Unicom, Omnitech, Hexie), or a crime syndicate (Camorra, North Jopok, Ndrangheta, Sinaloa, Solntsevskaya Bratva, Yamaguchi Gumi)." },
        { name: "Call in a Favor", description: "As an important asset, you can tap your relationship with your power network to pull strings. You have 2 favors (shown on the Suit table, increasing each level). At the start of each game session, you regain all favors. Sample favors include: Bodyguard (level 3), Background Check (level 5), Clean Up Crew (level 5), Disable Vehicle (level 9), Extraction Vehicle (any level), Aegis Particle Beam (level 17, costs 3 favors)." },
      ],
      2: [
        { name: "Moxy", description: "You can add your Charisma modifier to saving throws." },
        { name: "Sneak Attack", description: "Beginning at 2nd level, you know how to strike when the moment is right. Once per turn you can deal extra 1d6 damage with a finesse or ranged weapon if you have advantage on the attack roll. Increases to 2d6 at 5th, 3d6 at 8th, 4d6 at 11th, 5d6 at 14th, 6d6 at 17th, 7d6 at 20th." },
      ],
      3: [
        { name: "Career Path", description: "Your career path reflects the type of suit you are. It grants features at 3rd level and again at 6th, 9th, 13th, and 17th level. Subtypes: Commander (tactical leader and squad coordinator), G-Man (federal agent with investigative and enforcement powers), Shark (corporate operative who can also use hacking)." },
        { name: "Contact", description: "You gain a contact through your power network. You get additional contacts at levels 6, 9, 15, and 18." },
      ],
      4: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      5: [
        { name: "Promotion", description: "You have been promoted within your power network, granting you access to greater resources and authority. You gain 3 favors per session instead of 2. You receive additional promotions at levels 11, 14, and 18." },
        { name: "Inspiration (d8)", description: "Your Inspiration die increases to d8." },
      ],
      6: [
        { name: "Career Path Feature", description: "You gain a feature from your Career Path." },
        { name: "Contact (2nd)", description: "You gain your second contact through your power network." },
      ],
      7: [
        { name: "Contagious Moxy", description: "Allies within 9 meters of you can add your Charisma modifier to their saving throws as well." },
        { name: "Adaptive Learning", description: "You can gain proficiency in any skill for 24 hours after spending 10 minutes studying or practicing it. You can only maintain one such temporary proficiency at a time." },
      ],
      8: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      9: [
        { name: "Career Path Feature", description: "You gain a feature from your Career Path." },
        { name: "Contact (3rd)", description: "You gain your third contact through your power network." },
      ],
      10: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      11: [
        { name: "Promotion", description: "You have been promoted again. You now gain 6 favors per session." },
        { name: "Inspiration (d10)", description: "Your Inspiration die increases to d10." },
      ],
      12: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      13: [{ name: "Career Path Feature", description: "You gain a feature from your Career Path." }],
      14: [
        { name: "Promotion", description: "You have been promoted again. You now gain 7 favors per session." },
        { name: "Easy Inspiration", description: "You can now grant Inspiration as a free action (instead of a bonus action) on your turn." },
      ],
      15: [
        { name: "Inspiration (d12)", description: "Your Inspiration die increases to d12." },
        { name: "Contact (4th)", description: "You gain your fourth contact through your power network." },
      ],
      16: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      17: [{ name: "Career Path Feature", description: "You gain a feature from your Career Path." }],
      18: [
        { name: "Promotion", description: "You have been promoted to the highest levels of your network. You now gain 9 favors per session." },
        { name: "Contact (5th)", description: "You gain your fifth contact through your power network." },
      ],
      19: [{ name: "Ability Score Improvement", description: "You can increase one ability score by 2, or two ability scores by 1. You can't increase an ability score above your maximum using this feature." }],
      20: [{ name: "Superior Inspiration", description: "When you roll initiative and you have no Inspiration dice remaining, you regain one Inspiration die. Additionally, when you give a creature Inspiration, you can also give one to yourself." }],
    },
  },
];

