export interface UpgradeData {
  name: string;
  type: 'bioware' | 'cybernetic' | 'daemon';
  brand: string;
  cost: string;
  effectSummary: string;
  description: string;
  countsAsSlot: boolean;
}

export const UPGRADES: UpgradeData[] = [
  // ─── BIOWARE ────────────────────────────────────────────────────────────────
  {
    name: "Olfactors",
    type: "bioware",
    brand: "TruHound",
    cost: "シ100,000",
    effectSummary: "Able to discern scent to minute detail, and track by scent.",
    description: "Your sense of smell has been biohacked to have countless folds for increased surface area. You can recognize people's unique scent, track them easily (as long as it hasn't rained), and gain incredible details about anything you might eat or drink. While tracking people, you also learn their exact number, their sizes, and how long ago they passed through the area. If you are downwind of someone, it is impossible for them to hide from you, or keep themselves disguised without some major alteration of their scent. Additionally, you have advantage on Wisdom (Perception) checks that rely on smell.",
    countsAsSlot: true,
  },
  {
    name: "Amped Senses",
    type: "bioware",
    brand: "Sentinex",
    cost: "シ40,000",
    effectSummary: "Advantage on Perception and Investigation checks; +5 to passive Perception and Investigation.",
    description: "All of your senses have been biohacked to get a boost, providing you with much more empirical information about your environment. You gain advantage on Wisdom (Perception) and Intelligence (Investigation) ability checks. Additionally, your passive Perception and Investigation gain a +5 bonus.",
    countsAsSlot: true,
  },
  {
    name: "Cellular Rejuvenators",
    type: "bioware",
    brand: "Proteon",
    cost: "シ50,000",
    effectSummary: "It only requires 4 hours to obtain the benefits of a long rest.",
    description: "These handy little biobots swim around your body and streamline the efficiency of rest, speeding along all of the biochemical processes accomplished during sleep. You only need to spend 4 hours of downtime to take a long rest.",
    countsAsSlot: true,
  },
  {
    name: "Cellular Rejuvenators",
    type: "bioware",
    brand: "Hexie",
    cost: "シ200,000",
    effectSummary: "It only requires 2 hours to obtain the benefits of a long rest.",
    description: "These handy little biobots swim around your body and streamline the efficiency of rest. You only need to spend 2 hours of downtime to take a long rest.",
    countsAsSlot: true,
  },
  {
    name: "Cellular Rejuvenators",
    type: "bioware",
    brand: "Apollo",
    cost: "シ600,000",
    effectSummary: "It only requires 2 hours to obtain the benefits of a long rest, and you may take 2 long rests in a 24-hour period.",
    description: "You only need to spend 2 hours of downtime to take a long rest, and you may take 2 long rests in a 24-hour period.",
    countsAsSlot: true,
  },
  {
    name: "Cloakers",
    type: "bioware",
    brand: "Cryptek",
    cost: "シ60,000",
    effectSummary: "Become Invisible (must be naked or wearing transparency-capable clothing).",
    description: "Cloakers are biohacked chromatophores manufactured by Cryptek, residing in every visible surface of your body. They receive light from their environment and transmit it in a fashion that mimics nothing being in the way of the light at all. The effect is perfect camouflage, rendering you Invisible. Your outer surface must not be covered for the cloakers to be effective (you must be naked or wearing clothing with transparency capability), and cloakers have no effect on any of your equipment.",
    countsAsSlot: true,
  },
  {
    name: "Cosmetic Alteration",
    type: "bioware",
    brand: "Varies",
    cost: "シ5,000",
    effectSummary: "Alter your appearance aesthetically (no game-mechanical effect). Does not count as one of your 8 upgrade slots.",
    description: "The increased technological capacity for body alteration has opened up new creative realms. Options include moving angel or bat wings, color-shifting skin or hair, a moving tail, extra eyes, or whatever else the consumer can imagine. These upgrades have no in-game effect outside of their aesthetic and helping you fit in with certain crowds. At the player's discretion it can give you a strange or inhuman appearance. This upgrade does not count as one of your maximum allowed number of upgrades.",
    countsAsSlot: false,
  },
  {
    name: "Electric Organ",
    type: "bioware",
    brand: "Vitruvian",
    cost: "シ30,000",
    effectSummary: "As an action, target within 1.5m takes 10d6 electrical damage (DC 16 Dex save for half). Once per short rest.",
    description: "Like an electric eel or ray, you possess a transgenic organ that can generate an electrical discharge, boosted further by an accompanying implant. As an action, you can target anything within 1.5 meters. The target takes 10d6 electrical damage on a failed Dexterity save (DC 16), or half as much damage on a successful one. After using this ability, you must take a short rest to regain its use.",
    countsAsSlot: true,
  },
  {
    name: "Electric Organ",
    type: "bioware",
    brand: "Tezla",
    cost: "シ100,000",
    effectSummary: "As an action, target within 1.5m takes 10d6+25 electrical damage (DC 19 Dex save for half). Once per short rest.",
    description: "The target takes 10d6+25 electrical damage on a failed Dexterity save (DC 19), or half as much damage on a successful one. After using this ability, you must take a short rest to regain its use.",
    countsAsSlot: true,
  },
  {
    name: "Electric Organ",
    type: "bioware",
    brand: "Apollo",
    cost: "シ300,000",
    effectSummary: "As an action, target within 1.5m takes 10d6+50 electrical damage (DC 21 Dex save for half). Once per short rest.",
    description: "The target takes 10d6+50 electrical damage on a failed Dexterity save (DC 21), or half as much damage on a successful one. After using this ability, you must take a short rest to regain its use.",
    countsAsSlot: true,
  },
  {
    name: "Envenomers, Basic",
    type: "bioware",
    brand: "Proteon",
    cost: "シ60,000",
    effectSummary: "Produce and administer venoms (Hemovenom/Necrovenom/Neurovenom) via nematocysts, venom sac, or natural weapon. Once per short rest.",
    description: "A colony of bioengineered cells manufactures a virulent toxin. Choose your administration method (nematocysts, venom sac, or natural/retractable weapon) and one venom type:\n• Hemovenom: DC 11 Con save, 10 (3d6) poison damage on fail, poisoned for 1 hour; half on success.\n• Necrovenom: DC 11 Con save, 21 (6d6) poison damage on fail, half on success.\n• Neurovenom: DC 13 Con save, poisoned for 1 hour on fail; if failed by 5+, unconscious; if failed by 10+, death.\nYou must take a short rest before using it again.",
    countsAsSlot: true,
  },
  {
    name: "Hyper Reflexes",
    type: "bioware",
    brand: "Vitruvian",
    cost: "シ40,000",
    effectSummary: "+2 AC, advantage on Dexterity saves, additional action (limited) for 1 minute. Activate as bonus action. Once per long rest.",
    description: "This implant and biohack rewires your nervous system, flooding your body with stimulants, dramatically increasing your reflexes. You can use a bonus action to activate this ability, which lasts for one minute. While active, you gain a +2 bonus to AC, have advantage on Dexterity saving throws, and gain an additional action on each of your turns (usable only for Attack (one weapon attack only), Dash, Disengage, Hide, or Use an Object). When the effect ends, you can't move or take actions until after your next turn. You must take a long rest before using this ability again.",
    countsAsSlot: true,
  },
  {
    name: "Hyper Reflexes",
    type: "bioware",
    brand: "Apollo",
    cost: "シ100,000",
    effectSummary: "+2 AC, advantage on Dexterity saves, additional action (limited) for 1 minute. Activate as bonus action. Once per short rest.",
    description: "As Vitruvian Hyper Reflexes, but you must take only a short rest before using this ability again.",
    countsAsSlot: true,
  },
  {
    name: "Medicomp",
    type: "bioware",
    brand: "Nightingale",
    cost: "シ25,000",
    effectSummary: "Auto-stabilize at 0 HP; minimum 5 HP when rolling Hit Dice; advantage and resistance to poison.",
    description: "This system of implants and transgenic nanobots functions as an internal doctor. Benefits: automatic stabilization when knocked unconscious at 0 hit points; when you roll a Hit Die to regain hit points, the minimum number of hit points you regain is 5; advantage on saving throws against poison; resistance against poison damage.",
    countsAsSlot: true,
  },
  {
    name: "Medicomp",
    type: "bioware",
    brand: "Apollo",
    cost: "シ150,000",
    effectSummary: "All Nightingale benefits + store up to 20 drug doses (release as bonus action) + regain all HP on short rest.",
    description: "Includes all Nightingale medicomp benefits, plus: store up to 20 doses of drugs (one dose can be released and activated as a bonus action); all of your hit points are restored when you take a short rest.",
    countsAsSlot: true,
  },
  {
    name: "Pheromones",
    type: "bioware",
    brand: "Guanxi",
    cost: "シ50,000",
    effectSummary: "Proficiency (expertise if already proficient) in Insight, Deception, and Persuasion. Requires target can smell you.",
    description: "You've been biohacked to produce chemical messengers that have beguiling effects on people within smelling range. You gain proficiency in the Insight, Deception, and Persuasion skills. If you're already proficient in these skills, or take any of them later, your proficiency bonus is doubled for any check you make with that skill. This effect doesn't work unless the target is able to smell you.",
    countsAsSlot: true,
  },
  {
    name: "Photosynthesizers",
    type: "bioware",
    brand: "Proteon",
    cost: "シ20,000",
    effectSummary: "Only need sun, CO₂, and water to survive (no food required).",
    description: "Each transgenic cell of this biohack is loaded with chloroplasts and other cellular machinery that allows you to make your own food from sunlight, water, and carbon dioxide. As long as you drink water and have at least one hour of exposure to the sun each day, you do not need to eat.",
    countsAsSlot: true,
  },
  {
    name: "Respirators",
    type: "bioware",
    brand: "Proteon",
    cost: "シ25,000",
    effectSummary: "Ignore 2 levels of exhaustion; advantage on Constitution checks involving endurance.",
    description: "You are biohacked with specialized cells that metabolize lactic acid, reduce muscle exhaustion, and aid respiration and circulation throughout the entire body. This upgrade allows you to ignore 2 levels of exhaustion and gives you advantage on Constitution checks involving endurance.",
    countsAsSlot: true,
  },
  {
    name: "Synth Organs",
    type: "bioware",
    brand: "Nightingale",
    cost: "シ10,000",
    effectSummary: "+5 hit point maximum.",
    description: "Most of your essential organs are now backed up by artificial parallels. Your hit point maximum increases by 5.",
    countsAsSlot: true,
  },
  {
    name: "Synth Organs",
    type: "bioware",
    brand: "Proteon",
    cost: "シ30,000",
    effectSummary: "+10 hit point maximum.",
    description: "Most of your essential organs are now backed up by artificial parallels. Your hit point maximum increases by 10.",
    countsAsSlot: true,
  },
  {
    name: "Synth Organs",
    type: "bioware",
    brand: "Hexie",
    cost: "シ100,000",
    effectSummary: "+25 hit point maximum.",
    description: "Most of your essential organs are now backed up by artificial parallels. Your hit point maximum increases by 25.",
    countsAsSlot: true,
  },
  {
    name: "Synth Organs",
    type: "bioware",
    brand: "Apollo",
    cost: "シ400,000",
    effectSummary: "+45 hit point maximum.",
    description: "Most of your essential organs are now backed up by artificial parallels. Your hit point maximum increases by 45.",
    countsAsSlot: true,
  },
  {
    name: "Wall Crawling",
    type: "bioware",
    brand: "GekTek",
    cost: "シ30,000",
    effectSummary: "Climbing speed equal to regular speed; climb sheer surfaces without an Athletics check.",
    description: "Swathes of skin on your hands, feet, legs, and arms have been modified to shift into a microscopic fractalling surface, exploiting Van der Waals forces to cling to walls like a gecko. You can cause this effect to manifest as a free action, and you gain a climbing speed equal to your regular speed. Additionally, you can climb sheer surfaces without requiring a Strength (Athletics) check.",
    countsAsSlot: true,
  },
  {
    name: "Genetic Tweak",
    type: "bioware",
    brand: "Proteon",
    cost: "シ100,000",
    effectSummary: "You gain any one genetic enhancement of your choice from the genetic enhancement table.",
    description: "You undergo intense gene enhancement therapy, granting yourself a beneficial change. You may select any genetic enhancement from the genetic enhancement table.",
    countsAsSlot: true,
  },
  {
    name: "Genetic Tweak",
    type: "bioware",
    brand: "Apollo",
    cost: "シ300,000",
    effectSummary: "You gain any upgraded version of any genetic enhancement from the genetic enhancement table.",
    description: "You undergo intense gene enhancement therapy. You may select any upgraded version of any genetic enhancement from the genetic enhancement table.",
    countsAsSlot: true,
  },
  // ─── CYBERNETIC ─────────────────────────────────────────────────────────────
  {
    name: "Chemical Sensor",
    type: "cybernetic",
    brand: "TruHound",
    cost: "シ25,000",
    effectSummary: "Discern chemical compositions (including DNA) from anything that touches the sensor. Requires concentration; activated by Use an Object action.",
    description: "A sensor placed on your fingertip or tongue samples all chemicals that come into contact with it (solid, liquid, or gas). Poisons, DNA, and all other chemical compositions can be discerned. With proper authorization or hacking ability, the sampled DNA can be looked up in governmental databases. This upgrade requires concentration and is activated by the Use an Object action.",
    countsAsSlot: true,
  },
  {
    name: "Cyberoptics",
    type: "cybernetic",
    brand: "Vitruvian",
    cost: "シ30,000",
    effectSummary: "Darkvision 36m; microvision (50× magnification, concentration); macrovision (see clearly 1 km away, concentration); flashbang protection via smart lenses.",
    description: "Replaces your original eyes with superior artificial eyes. Abilities: Darkvision (see normally in darkness up to 36 meters); Microvision (magnify up to 50× with conscious thought, powerful enough to see individual cells — requires concentration); Macrovision (built-in binoculars, see clearly up to 1 km — requires concentration); Protection (smart polarized lenses auto-darken against any bright light, including flashbangs).",
    countsAsSlot: true,
  },
  {
    name: "Cyberoptics",
    type: "cybernetic",
    brand: "Sentinex",
    cost: "シ150,000",
    effectSummary: "All Vitruvian benefits + spectrum vision (see invisible, treat lightly obscured as clear) + penetration vision (x-ray up to 15m, requires concentration, disadvantage on attacks/Dex checks).",
    description: "Includes all Vitruvian cyberoptics abilities plus: Spectrum Vision (enhanced visible and nonvisible light, infrared, UV, microwaves — lightly obscured treated as clear, heavily obscured as lightly obscured, see invisible creatures — requires concentration); Penetration Vision (radar/T-ray/infrared/ultrasound triangulation, see through smoke, clothes, flesh, and walls up to 15 meters — requires concentration, imposes disadvantage on attack rolls and Dex checks, move at 3/4 speed).",
    countsAsSlot: true,
  },
  {
    name: "Cybernetic Arm",
    type: "cybernetic",
    brand: "Vitruvian",
    cost: "シ25,000",
    effectSummary: "Strength score considered 14 for one-arm checks; unarmed strikes deal 1d4 (hard-knuckle).",
    description: "One arm and surrounding tissue is replaced with a prosthetic version. The Strength score provided only applies to checks involving one arm (including reducing recoil for one-handed firearms and melee attacks with one-handed weapons). Vitruvian: unarmed strikes deal 1d4 damage with the hard-knuckle trait; Strength ability score is considered 14 for single-arm purposes.",
    countsAsSlot: true,
  },
  {
    name: "Cybernetic Arm",
    type: "cybernetic",
    brand: "Hexie",
    cost: "シ150,000",
    effectSummary: "Strength score considered 22 for one-arm checks; unarmed strikes deal 1d6 (hard-knuckle).",
    description: "One arm and surrounding tissue is replaced with a prosthetic version. Hexie: unarmed strikes deal 1d6 damage with the hard-knuckle trait; Strength ability score is considered 22 for single-arm purposes.",
    countsAsSlot: true,
  },
  {
    name: "Cybernetic Arm",
    type: "cybernetic",
    brand: "Omnitech",
    cost: "シ500,000",
    effectSummary: "Strength score considered 28 for one-arm checks; unarmed strikes deal 1d8 (hard-knuckle).",
    description: "One arm and surrounding tissue is replaced with a prosthetic version. Omnitech: unarmed strikes deal 1d8 damage with the hard-knuckle trait; Strength ability score is considered 28 for single-arm purposes.",
    countsAsSlot: true,
  },
  {
    name: "Dermal Weave",
    type: "cybernetic",
    brand: "Vitruvian",
    cost: "シ8,000",
    effectSummary: "2 Damage Reduction vs. bludgeoning, slashing, and piercing. Does not stack with armor.",
    description: "This biohack produces high-strength synthetic fibers similar to spider silk which are woven throughout your skin. You gain 2 Damage Reduction versus bludgeoning, slashing, and piercing. Does not stack with armor.",
    countsAsSlot: true,
  },
  {
    name: "Dermal Weave",
    type: "cybernetic",
    brand: "Hexie",
    cost: "シ35,000",
    effectSummary: "4 Damage Reduction vs. bludgeoning, slashing, and piercing. Does not stack with armor.",
    description: "High-strength synthetic fibers woven throughout your skin. You gain 4 Damage Reduction versus bludgeoning, slashing, and piercing. Does not stack with armor.",
    countsAsSlot: true,
  },
  {
    name: "Dermal Weave",
    type: "cybernetic",
    brand: "Validerm",
    cost: "シ150,000",
    effectSummary: "6 Damage Reduction vs. bludgeoning, slashing, and piercing. Does not stack with armor.",
    description: "High-strength synthetic fibers woven throughout your skin. You gain 6 Damage Reduction versus bludgeoning, slashing, and piercing. Does not stack with armor.",
    countsAsSlot: true,
  },
  {
    name: "Gills",
    type: "cybernetic",
    brand: "Triton",
    cost: "シ25,000",
    effectSummary: "Breathe underwater (as long as it is oxygenated).",
    description: "Artificial gills allow oxygen consumption from water. A selectively permeable membrane encases the lungs, extracting oxygen from water and allowing gases associated with respiration through but keeping water out. You can breathe underwater as long as it is oxygenated. When you surface, the lungful of water is expelled through the mouth.",
    countsAsSlot: true,
  },
  {
    name: "Hyper Jumping",
    type: "cybernetic",
    brand: "Vitruvian",
    cost: "シ40,000",
    effectSummary: "Jumping distances tripled; fall up to 9m without taking damage.",
    description: "This biohack adds extra spring to your leg muscles through resilin and specialized synthetic muscles. This upgrade doesn't stack with any other ability that increases your jumping distance. Vitruvian: jumping distance is tripled; additionally, these fibers absorb shock from falling, allowing you to fall 9 meters (instead of 3) without taking damage.",
    countsAsSlot: true,
  },
  {
    name: "Hyper Jumping",
    type: "cybernetic",
    brand: "Thumper",
    cost: "シ120,000",
    effectSummary: "Jumping distances tripled; fall up to 9m without damage; any Strength (Athletics) jump check below 20 is automatically raised to 20.",
    description: "All the benefits of Vitruvian Hyper Jumping, plus any Strength (Athletics) checks related to jumping that are below 20 are automatically raised to 20.",
    countsAsSlot: true,
  },
  {
    name: "Muscle Weave",
    type: "cybernetic",
    brand: "Vitruvian",
    cost: "シ20,000",
    effectSummary: "+2 Strength; Strength maximum increases to 22.",
    description: "The muscle weave biohack is a network of ultra-strong musculoskeletal fibers that support and enhance muscle contractions. Your Strength score is increased by +2, and your maximum Strength score is now 22.",
    countsAsSlot: true,
  },
  {
    name: "Muscle Weave",
    type: "cybernetic",
    brand: "Ronin",
    cost: "シ75,000",
    effectSummary: "+4 Strength; Strength maximum increases to 24.",
    description: "The muscle weave biohack is a network of ultra-strong musculoskeletal fibers. Your Strength score is increased by +4, and your maximum Strength score is now 24.",
    countsAsSlot: true,
  },
  {
    name: "Muscle Weave",
    type: "cybernetic",
    brand: "Hexie",
    cost: "シ200,000",
    effectSummary: "+6 Strength; Strength maximum increases to 26.",
    description: "The muscle weave biohack is a network of ultra-strong musculoskeletal fibers. Your Strength score is increased by +6, and your maximum Strength score is now 26.",
    countsAsSlot: true,
  },
  {
    name: "Muscle Weave",
    type: "cybernetic",
    brand: "Omnitech",
    cost: "シ500,000",
    effectSummary: "+8 Strength; Strength maximum increases to 28.",
    description: "The muscle weave biohack is a network of ultra-strong musculoskeletal fibers. Your Strength score is increased by +8, and your maximum Strength score is now 28.",
    countsAsSlot: true,
  },
  {
    name: "Polyguise",
    type: "cybernetic",
    brand: "Omnitech",
    cost: "シ30,000",
    effectSummary: "Alter your face and voice; DC 16 Intelligence (Investigation) to detect the disguise. Can mimic a specific person's face.",
    description: "This biohack enables you to adopt any number of human appearances and voices. Your face and larynx are reconstructed with artificial bones, cartilage, and muscles rearrangeable with conscious thought. Artificial hair can turn any color or length (baldness up to 1 meter), and skin pigment can change to any uniform color. A full turn of concentration initiates a change. You can mimic a specific person's face. To detect your disguise, a person must succeed on an Intelligence (Investigation) check against DC 16 — but this doesn't reveal your true identity. If speaking to subjects who know you (or the person you're imitating), succeed at a Charisma (Deception) check against their passive Insight score.",
    countsAsSlot: true,
  },
  {
    name: "Reinforced Skeleton",
    type: "cybernetic",
    brand: "Hexie",
    cost: "シ75,000",
    effectSummary: "Resistance to bludgeoning damage; unarmed strikes gain the hard-knuckle property (+2 damage).",
    description: "Your skeleton is reinforced with high-strength synthetics and metallic alloys, rendering your bones as strong as nanocarbon steel. This cyberware grants resistance to bludgeoning damage, and grants the hard-knuckle property to your unarmed strikes (+2 damage).",
    countsAsSlot: true,
  },
  {
    name: "Retractable Blade",
    type: "cybernetic",
    brand: "Vitruvian",
    cost: "シ25,000",
    effectSummary: "Light finesse simple melee weapon (wrist nanoblade or fingertip claws). Deals 2d4 armor-piercing piercing or slashing damage.",
    description: "An implanted nanoblade springs from your wrist, or claws unsheathe from your fingertips (your choice). Unsheathable as a free action; they are a light finesse simple melee weapon. Vitruvian: deals 2d4 piercing or slashing armor-piercing damage.",
    countsAsSlot: true,
  },
  {
    name: "Retractable Blade",
    type: "cybernetic",
    brand: "Ronin",
    cost: "シ50,000",
    effectSummary: "Light finesse simple melee weapon. Deals 2d6 armor-piercing piercing or slashing damage.",
    description: "An implanted nanoblade or claw, unsheathable as a free action; light finesse simple melee weapon. Ronin: deals 2d6 piercing or slashing armor-piercing damage.",
    countsAsSlot: true,
  },
  {
    name: "Retractable Blade",
    type: "cybernetic",
    brand: "Hexie",
    cost: "シ100,000",
    effectSummary: "Light finesse simple melee weapon. Deals 2d8 armor-piercing piercing or slashing damage.",
    description: "An implanted nanoblade or claw, unsheathable as a free action; light finesse simple melee weapon. Hexie: deals 2d8 piercing or slashing armor-piercing damage.",
    countsAsSlot: true,
  },
  {
    name: "Retractable Blade",
    type: "cybernetic",
    brand: "Excalibur",
    cost: "シ300,000",
    effectSummary: "Light finesse simple melee weapon. Deals 2d8 armor-piercing damage; critical hit on a roll of 18–20.",
    description: "An implanted nanoblade or claw, unsheathable as a free action; light finesse simple melee weapon. Excalibur: deals 2d8 piercing or slashing armor-piercing damage, and attacks with it score a critical hit on a roll of 18–20.",
    countsAsSlot: true,
  },
  {
    name: "Shock Core",
    type: "cybernetic",
    brand: "Tezla",
    cost: "シ75,000",
    effectSummary: "Melee attacks deal +1d4 electrical damage (unarmed: +1d8) for 1 minute. Activate as bonus action. Once per long rest.",
    description: "You are wired with an internal battery and wiring that allows you to discharge intense electrical shocks through your melee attacks. Activate as a bonus action; remains active for 1 minute; long rest required to use again. While active — Tezla: your melee attacks deal an additional 1d4 electrical damage, or 1d8 electrical damage if they are unarmed strikes.",
    countsAsSlot: true,
  },
  {
    name: "Shock Core",
    type: "cybernetic",
    brand: "Omnitech",
    cost: "シ200,000",
    effectSummary: "Melee attacks deal +1d6 electrical damage (unarmed: +1d12) for 1 minute. Activate as bonus action. Once per long rest.",
    description: "You are wired with an internal battery and wiring that allows you to discharge intense electrical shocks through your melee attacks. Activate as a bonus action; remains active for 1 minute; long rest required to use again. While active — Omnitech: your melee attacks deal an additional 1d6 electrical damage, or 1d12 electrical damage if they are unarmed strikes.",
    countsAsSlot: true,
  },
  {
    name: "Sprint Boost",
    type: "cybernetic",
    brand: "Vitruvian",
    cost: "シ20,000",
    effectSummary: "Speed increases by 3 meters.",
    description: "This augmentation strengthens fast-twitch muscles in your legs. Your Speed increases by 3 meters.",
    countsAsSlot: true,
  },
  {
    name: "Sprint Boost",
    type: "cybernetic",
    brand: "Thumper",
    cost: "シ60,000",
    effectSummary: "Speed increases by 6 meters.",
    description: "This augmentation strengthens fast-twitch muscles in your legs. Your Speed increases by 6 meters.",
    countsAsSlot: true,
  },
  {
    name: "Sprint Boost",
    type: "cybernetic",
    brand: "Omnitech",
    cost: "シ175,000",
    effectSummary: "Speed increases by 9 meters.",
    description: "This augmentation strengthens fast-twitch muscles in your legs. Your Speed increases by 9 meters.",
    countsAsSlot: true,
  },
  {
    name: "Sprint Boost",
    type: "cybernetic",
    brand: "Blitz-Cat",
    cost: "シ500,000",
    effectSummary: "Speed increases by 12 meters.",
    description: "This augmentation strengthens fast-twitch muscles in your legs. Your Speed increases by 12 meters.",
    countsAsSlot: true,
  },
  {
    name: "Stun Knuckles",
    type: "cybernetic",
    brand: "Tezla",
    cost: "シ25,000",
    effectSummary: "Unarmed strikes gain hard-knuckle. On a successful unarmed hit, target makes DC 10 Constitution save or is stunned until end of their turn.",
    description: "Your knuckles, elbows, shins, and other useful impact areas are reinforced with high-strength conductive materials that can deliver muscle-paralyzing shocks. Whenever you successfully hit someone with an unarmed attack, they must make a DC 10 Constitution save, or be stunned until the end of their turn.",
    countsAsSlot: true,
  },
  {
    name: "Subdermal Plates",
    type: "cybernetic",
    brand: "Vitruvian",
    cost: "シ5,000",
    effectSummary: "+3 AC. Counts as Light Armor; use whichever is higher if you also wear armor (does not stack).",
    description: "Vital areas of your body are protected by nanocarbon plates placed under your skin, replacing bone in some cases. These plates count as wearing Light Armor. If you suit up in armor, you use whatever bonus is higher; they do not stack. Vitruvian: your AC increases by 3.",
    countsAsSlot: true,
  },
  {
    name: "Subdermal Plates",
    type: "cybernetic",
    brand: "Ronin",
    cost: "シ25,000",
    effectSummary: "+5 AC. Counts as Light Armor; use whichever is higher if you also wear armor (does not stack).",
    description: "Vital areas of your body are protected by nanocarbon plates placed under your skin. Counts as wearing Light Armor; use whichever is higher if also wearing armor. Ronin: your AC increases by 5.",
    countsAsSlot: true,
  },
  {
    name: "Subdermal Plates",
    type: "cybernetic",
    brand: "Validerm",
    cost: "シ120,000",
    effectSummary: "+7 AC. Counts as Light Armor; use whichever is higher if you also wear armor (does not stack).",
    description: "Vital areas of your body are protected by nanocarbon plates placed under your skin. Counts as wearing Light Armor; use whichever is higher if also wearing armor. Validerm: your AC increases by 7.",
    countsAsSlot: true,
  },
  // ─── DAEMON ─────────────────────────────────────────────────────────────────
  {
    name: "Amped Confidence",
    type: "daemon",
    brand: "Hyperborea",
    cost: "シ25,000",
    effectSummary: "+2 Charisma; Charisma maximum increases to 22.",
    description: "Your brain chemistry is biohacked to provide you with optimal self-assuredness, charm, and debonair. Hyperborea: Charisma score increases by +2, and your maximum Charisma score is now 22.",
    countsAsSlot: true,
  },
  {
    name: "Amped Confidence",
    type: "daemon",
    brand: "Guanxi",
    cost: "シ150,000",
    effectSummary: "+4 Charisma; Charisma maximum increases to 24.",
    description: "Your brain chemistry is biohacked for optimal self-assuredness and charm. Guanxi: Charisma score increases by +4, and your maximum Charisma score is now 24.",
    countsAsSlot: true,
  },
  {
    name: "Cognitive Boost",
    type: "daemon",
    brand: "Hyperborea",
    cost: "シ25,000",
    effectSummary: "+2 Intelligence; Intelligence maximum increases to 22.",
    description: "Your general intellect is enhanced by rewiring key neural pathways, in conjunction with a brain-computer interface chip. Hyperborea: Intelligence score is increased by +2, and your maximum Intelligence score is now 22.",
    countsAsSlot: true,
  },
  {
    name: "Cognitive Boost",
    type: "daemon",
    brand: "Satori",
    cost: "シ150,000",
    effectSummary: "+4 Intelligence; Intelligence maximum increases to 24.",
    description: "Your general intellect is enhanced by rewiring key neural pathways. Satori: Intelligence score is increased by +4, and your maximum Intelligence score is now 24.",
    countsAsSlot: true,
  },
  {
    name: "Daemon Firewall",
    type: "daemon",
    brand: "Hexie",
    cost: "シ5,000",
    effectSummary: "+2 bonus on saving throws vs. mind hacks. Requires concentration.",
    description: "You have some protection versus mind hacking. While active, you gain a +2 bonus on any saving throws made to resist mind hacks. Requires concentration.",
    countsAsSlot: true,
  },
  {
    name: "Daemon Firewall",
    type: "daemon",
    brand: "Omnitech",
    cost: "シ30,000",
    effectSummary: "Advantage on saving throws vs. mind hacks. Requires concentration.",
    description: "You have some protection versus mind hacking. While active, you gain advantage on any saving throws made to resist mind hacks. Requires concentration.",
    countsAsSlot: true,
  },
  {
    name: "Custom Daemon OS",
    type: "daemon",
    brand: "Hexie",
    cost: "シ40,000",
    effectSummary: "Your daemon can run any Bot AI from the Goods & Services chapter (one at a time).",
    description: "Your daemon has been upgraded to accommodate different AI, allowing you to house superior AI than the base one. Hexie: you can purchase and install any of the bot AI described in the Robots section of Chapter 4: Goods and Services. Only one bot may be installed as your AI at any given time.",
    countsAsSlot: true,
  },
  {
    name: "Custom Daemon OS",
    type: "daemon",
    brand: "Omnitech",
    cost: "シ250,000",
    effectSummary: "All Hexie benefits + combat firmware allowing your daemon AI to take control of your body (with Extra Attack, weapon proficiency, and unarmed 1d6+STR).",
    description: "Includes all Hexie Custom Daemon OS benefits. Additionally, your daemon has been upgraded with firmware that allows it to take control of your motor functions. Possession rules: 1 action to transfer control; it can take actions normally; uses your proficiency bonus and STR/DEX/CON scores; cannot use your skill proficiencies or class features; has Extra Attack (as Gunfighter), proficiency in all weapons; as a bonus action during Attack, makes one unarmed strike (1d6+STR). Mind hacks still affect both you and your daemon AI using your saving throws. You retain your senses and can still launch hacks, use telepresence, dive in the WDS, or communicate.",
    countsAsSlot: true,
  },
  {
    name: "Dataport",
    type: "daemon",
    brand: "Varies",
    cost: "シ3,000",
    effectSummary: "Hardline port to connect your daemon directly to devices without wireless. Bypasses wireless jamming/detection.",
    description: "You can hook up your daemon directly to other devices that have jacks without using wireless. Essential to interfacing with computers that lack wireless capability, which is common for CCTV and databases containing sensitive data. This implant bypasses attempts to jam or detect wireless signals.",
    countsAsSlot: true,
  },
  {
    name: "Heightened Focus",
    type: "daemon",
    brand: "Hyperborea",
    cost: "シ25,000",
    effectSummary: "+2 Wisdom; Wisdom maximum increases to 22.",
    description: "You biohack your brain, augmenting pathways and amplifying neurotransmitters and hormones relating to conscious awareness. Hyperborea: Wisdom score increases by +2, and your maximum Wisdom score is now 22.",
    countsAsSlot: true,
  },
  {
    name: "Heightened Focus",
    type: "daemon",
    brand: "Satori",
    cost: "シ150,000",
    effectSummary: "+4 Wisdom; Wisdom maximum increases to 24.",
    description: "You biohack your brain for greater mindfulness, alertness, and awareness. Satori: Wisdom score increases by +4, and your maximum Wisdom score is now 24.",
    countsAsSlot: true,
  },
  {
    name: "Motorchip",
    type: "daemon",
    brand: "Hexie",
    cost: "シ25,000",
    effectSummary: "+2 Dexterity; Dexterity maximum increases to 22.",
    description: "This implant optimizes your motor skills, giving you greater balance and hand-eye coordination. Hexie: Dexterity score is increased by +2, and your maximum Dexterity score is now 22.",
    countsAsSlot: true,
  },
  {
    name: "Motorchip",
    type: "daemon",
    brand: "Omnitech",
    cost: "シ150,000",
    effectSummary: "+4 Dexterity; Dexterity maximum increases to 24.",
    description: "This implant optimizes your motor skills. Omnitech: Dexterity score is increased by +4, and your maximum Dexterity score is now 24.",
    countsAsSlot: true,
  },
  {
    name: "Multitasking Processor",
    type: "daemon",
    brand: "Omnitech",
    cost: "シ75,000",
    effectSummary: "You may concentrate on one additional effect (run one more program that requires concentration than normal).",
    description: "You add a general brain-computer interface processor, enabling you to run an additional program or upgrade that requires concentration (you may concentrate on one more effect than normal).",
    countsAsSlot: true,
  },
  {
    name: "Skill Chip",
    type: "daemon",
    brand: "Hyperborea",
    cost: "シ25,000",
    effectSummary: "Run 1 skillsoft (grants proficiency in that skill). Each skillsoft costs シ1,000 extra. Requires concentration; 10 min to load.",
    description: "This chip implant allows you to run skillsoft — specialized software that grants you competency in a skill. Particular skillsoft must be purchased separately and each costs シ1,000. Hyperborea: while running a particular skillsoft, you gain proficiency in that skill. It takes 10 minutes to load up a particular skillsoft. Requires concentration.",
    countsAsSlot: true,
  },
  {
    name: "Skill Chip",
    type: "daemon",
    brand: "Omnitech",
    cost: "シ100,000",
    effectSummary: "Run 2 skillsoft simultaneously. Each skillsoft costs シ1,000 extra. Requires concentration; 10 min to load.",
    description: "This chip implant allows you to run skillsoft. Omnitech: functions like the Hyperborea Skill Chip, but you can run two skillsoft at once.",
    countsAsSlot: true,
  },
  {
    name: "Targeting Computer",
    type: "daemon",
    brand: "Ronin",
    cost: "シ25,000",
    effectSummary: "+2 bonus to all attack rolls.",
    description: "You get a targeting implant and software that increases your accuracy. Ronin: you gain a +2 bonus to all attack rolls.",
    countsAsSlot: true,
  },
  {
    name: "Targeting Computer",
    type: "daemon",
    brand: "Hexie",
    cost: "シ100,000",
    effectSummary: "+3 bonus to all attack rolls.",
    description: "You get a targeting implant and software that increases your accuracy. Hexie: you gain a +3 bonus to all attack rolls.",
    countsAsSlot: true,
  },
  {
    name: "Targeting Computer",
    type: "daemon",
    brand: "Omnitech",
    cost: "シ400,000",
    effectSummary: "+4 bonus to all attack rolls.",
    description: "You get a targeting implant and software that increases your accuracy. Omnitech: you gain a +4 bonus to all attack rolls.",
    countsAsSlot: true,
  },
];

